import { PrefectureName, SpecialPattern } from './types';

export const getPrefectureRegexPatterns = (): SpecialPattern[] => {
  return [
    [PrefectureName.HOKKAIDO, new RegExp(`^${PrefectureName.HOKKAIDO}?`)],
    [PrefectureName.AOMORI, new RegExp(`^${PrefectureName.AOMORI}?`)],
    [PrefectureName.IWATE, new RegExp(`^${PrefectureName.IWATE}?`)],
    [PrefectureName.MIYAGI, new RegExp(`^${PrefectureName.MIYAGI}?`)],
    [PrefectureName.YAMAGATA, new RegExp(`^${PrefectureName.YAMAGATA}?`)],
    [PrefectureName.AKITA, new RegExp(`^${PrefectureName.AKITA}?`)],
    [PrefectureName.FUKUSHIMA, new RegExp(`^${PrefectureName.FUKUSHIMA}?`)],
    [PrefectureName.IBARAKI, new RegExp(`^${PrefectureName.IBARAKI}?`)],
    [PrefectureName.TOCHIGI, new RegExp(`^${PrefectureName.TOCHIGI}?`)],
    [PrefectureName.GUMMA, new RegExp(`^${PrefectureName.GUMMA}?`)],
    [PrefectureName.SAITAMA, new RegExp(`^${PrefectureName.SAITAMA}?`)],
    [PrefectureName.CHIBA, new RegExp(`^${PrefectureName.CHIBA}?`)],
    [PrefectureName.TOKYO, new RegExp(`^${PrefectureName.TOKYO}?`)],
    [PrefectureName.KANAGAWA, new RegExp(`^${PrefectureName.KANAGAWA}?`)],
    [PrefectureName.YAMANASHI, new RegExp(`^${PrefectureName.YAMANASHI}?`)],
    [PrefectureName.NAGANO, new RegExp(`^${PrefectureName.NAGANO}?`)],
    [PrefectureName.NIIGATA, new RegExp(`^${PrefectureName.NIIGATA}?`)],
    [PrefectureName.TOYAMA, new RegExp(`^${PrefectureName.TOYAMA}?`)],
    [PrefectureName.ISHIKAWA, new RegExp(`^${PrefectureName.ISHIKAWA}?`)],
    [PrefectureName.FUKUI, new RegExp(`^${PrefectureName.FUKUI}?`)],
    [PrefectureName.SHIZUOKA, new RegExp(`^${PrefectureName.SHIZUOKA}?`)],
    [PrefectureName.AICHI, new RegExp(`^${PrefectureName.AICHI}?`)],
    [PrefectureName.GIFU, new RegExp(`^${PrefectureName.GIFU}?`)],
    [PrefectureName.MIE, new RegExp(`^${PrefectureName.MIE}?`)],
    [PrefectureName.SHIGA, new RegExp(`^${PrefectureName.SHIGA}?`)],
    [PrefectureName.KYOTO, new RegExp(`^${PrefectureName.KYOTO}?`)],
    [PrefectureName.OSAKA, new RegExp(`^${PrefectureName.OSAKA}?`)],
    [PrefectureName.HYOGO, new RegExp(`^${PrefectureName.HYOGO}?`)],
    [PrefectureName.NARA, new RegExp(`^${PrefectureName.NARA}?`)],
    [PrefectureName.WAKAYAMA, new RegExp(`^${PrefectureName.WAKAYAMA}?`)],
    [PrefectureName.OKAYAMA, new RegExp(`^${PrefectureName.OKAYAMA}?`)],
    [PrefectureName.HIROSHIMA, new RegExp(`^${PrefectureName.HIROSHIMA}?`)],
    [PrefectureName.TOTTORI, new RegExp(`^${PrefectureName.TOTTORI}?`)],
    [PrefectureName.SHIMANE, new RegExp(`^${PrefectureName.SHIMANE}?`)],
    [PrefectureName.YAMAGUCHI, new RegExp(`^${PrefectureName.YAMAGUCHI}?`)],
    [PrefectureName.TOKUSHIMA, new RegExp(`^${PrefectureName.TOKUSHIMA}?`)],
    [PrefectureName.KAGAWA, new RegExp(`^${PrefectureName.KAGAWA}?`)],
    [PrefectureName.EHIME, new RegExp(`^${PrefectureName.EHIME}?`)],
    [PrefectureName.KOCHI, new RegExp(`^${PrefectureName.KOCHI}?`)],
    [PrefectureName.FUKUOKA, new RegExp(`^${PrefectureName.FUKUOKA}?`)],
    [PrefectureName.SAGA, new RegExp(`^${PrefectureName.SAGA}?`)],
    [PrefectureName.NAGASAKI, new RegExp(`^${PrefectureName.NAGASAKI}?`)],
    [PrefectureName.OITA, new RegExp(`^${PrefectureName.OITA}?`)],
    [PrefectureName.KUMAMOTO, new RegExp(`^${PrefectureName.KUMAMOTO}?`)],
    [PrefectureName.MIYAZAKI, new RegExp(`^${PrefectureName.MIYAZAKI}?`)],
    [PrefectureName.KAGOSHIMA, new RegExp(`^${PrefectureName.KAGOSHIMA}?`)],
    [PrefectureName.OKINAWA, new RegExp(`^${PrefectureName.OKINAWA}?`)]
  ];
};