import {PrefectureName, SpecialPattern} from './types';

export const getPrefectureRegexPatterns = (): SpecialPattern[] => {
  return [
    [PrefectureName.HOKKAIDO, `^${PrefectureName.HOKKAIDO}?`],
    [PrefectureName.AOMORI, `^${PrefectureName.AOMORI}?`],
    [PrefectureName.IWATE, `^${PrefectureName.IWATE}?`],
    [PrefectureName.MIYAGI, `^${PrefectureName.MIYAGI}?`],
    [PrefectureName.YAMAGATA, `^${PrefectureName.YAMAGATA}?`],
    [PrefectureName.AKITA, `^${PrefectureName.AKITA}?`],
    [PrefectureName.FUKUSHIMA, `^${PrefectureName.FUKUSHIMA}?`],
    [PrefectureName.IBARAKI, `^${PrefectureName.IBARAKI}?`],
    [PrefectureName.TOCHIGI, `^${PrefectureName.TOCHIGI}?`],
    [PrefectureName.GUMMA, `^${PrefectureName.GUMMA}?`],
    [PrefectureName.SAITAMA, `^${PrefectureName.SAITAMA}?`],
    [PrefectureName.CHIBA, `^${PrefectureName.CHIBA}?`],
    [PrefectureName.TOKYO, `^${PrefectureName.TOKYO}?`],
    [PrefectureName.KANAGAWA, `^${PrefectureName.KANAGAWA}?`],
    [PrefectureName.YAMANASHI, `^${PrefectureName.YAMANASHI}?`],
    [PrefectureName.NAGANO, `^${PrefectureName.NAGANO}?`],
    [PrefectureName.NIIGATA, `^${PrefectureName.NIIGATA}?`],
    [PrefectureName.TOYAMA, `^${PrefectureName.TOYAMA}?`],
    [PrefectureName.ISHIKAWA, `^${PrefectureName.ISHIKAWA}?`],
    [PrefectureName.FUKUI, `^${PrefectureName.FUKUI}?`],
    [PrefectureName.SHIZUOKA, `^${PrefectureName.SHIZUOKA}?`],
    [PrefectureName.AICHI, `^${PrefectureName.AICHI}?`],
    [PrefectureName.GIFU, `^${PrefectureName.GIFU}?`],
    [PrefectureName.MIE, `^${PrefectureName.MIE}?`],
    [PrefectureName.SHIGA, `^${PrefectureName.SHIGA}?`],
    [PrefectureName.KYOTO, `^${PrefectureName.KYOTO}?`],
    [PrefectureName.OSAKA, `^${PrefectureName.OSAKA}?`],
    [PrefectureName.HYOGO, `^${PrefectureName.HYOGO}?`],
    [PrefectureName.NARA, `^${PrefectureName.NARA}?`],
    [PrefectureName.WAKAYAMA, `^${PrefectureName.WAKAYAMA}?`],
    [PrefectureName.OKAYAMA, `^${PrefectureName.OKAYAMA}?`],
    [PrefectureName.HIROSHIMA, `^${PrefectureName.HIROSHIMA}?`],
    [PrefectureName.TOTTORI, `^${PrefectureName.TOTTORI}?`],
    [PrefectureName.SHIMANE, `^${PrefectureName.SHIMANE}?`],
    [PrefectureName.YAMAGUCHI, `^${PrefectureName.YAMAGUCHI}?`],
    [PrefectureName.TOKUSHIMA, `^${PrefectureName.TOKUSHIMA}?`],
    [PrefectureName.KAGAWA, `^${PrefectureName.KAGAWA}?`],
    [PrefectureName.EHIME, `^${PrefectureName.EHIME}?`],
    [PrefectureName.KOCHI, `^${PrefectureName.KOCHI}?`],
    [PrefectureName.FUKUOKA, `^${PrefectureName.FUKUOKA}?`],
    [PrefectureName.SAGA, `^${PrefectureName.SAGA}?`],
    [PrefectureName.NAGASAKI, `^${PrefectureName.NAGASAKI}?`],
    [PrefectureName.OITA, `^${PrefectureName.OITA}?`],
    [PrefectureName.KUMAMOTO, `^${PrefectureName.KUMAMOTO}?`],
    [PrefectureName.MIYAZAKI, `^${PrefectureName.MIYAZAKI}?`],
    [PrefectureName.KAGOSHIMA, `^${PrefectureName.KAGOSHIMA}?`],
    [PrefectureName.OKINAWA, `^${PrefectureName.OKINAWA}?`],
  ];
};
