name: abr
services:
  abrg_app:
    build:
      context: ..
      dockerfile: abrg/Dockerfile
    container_name: abrg_cli
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      PORT: ${PORT}
      GIN_MODE: ${GIN_MODE}
      LOG_LEVEL: ${LOG_LEVEL}
      # CACHE_PATH: ${CACHE_PATH:-~/.abrg/cache/abrg.duckdb}
    ports:
      - "3000:3000"
    volumes:
      - abrg_cache:/root/.abrg/cache

volumes:
  abrg_cache: