package issues

import (
	"abrg/internal/model"
	"testing"
)

// TestIssue78 tests various address normalization patterns with missing residential data
// Issue #78: 住居番号データなしでの街区レベルマッチング
func TestIssue78(t *testing.T) {
	runNormalizeTests(t, []normalizeTestCase{
		{
			name: "issue78-1a [東京都港区南麻布５－１０－２７ー５１６]",
			query: model.MatchQuery{
				Address:  "東京都港区南麻布５－１０－２７ー５１６",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "東京都港区南麻布5丁目10",
			wantUnmatchedAddress: []string{"-27-516"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "港区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "南麻布",
				FieldChome:        "5丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "10",
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue78-1b [東京都港区南麻布五丁目１０番２７号５１６]",
			query: model.MatchQuery{
				Address:  "東京都港区南麻布五丁目１０番２７号５１６",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "東京都港区南麻布5丁目10",
			wantUnmatchedAddress: []string{"-27", "516"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "港区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "南麻布",
				FieldChome:        "5丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "10",
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue78-2a [広島県広島市安佐北区口田南４丁目２１番７号]",
			query: model.MatchQuery{
				Address:  "広島県広島市安佐北区口田南４丁目２１番７号",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "広島県広島市安佐北区口田南四丁目21-7",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "広島県",
				FieldCounty:       nil,
				FieldCity:         "広島市",
				FieldWard:         "安佐北区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "口田南",
				FieldChome:        "四丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "21",
				FieldRsdtNum:      "7",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue78-2b [広島市安佐北区口田南四丁目２１番７号]",
			query: model.MatchQuery{
				Address:  "広島市安佐北区口田南四丁目２１番７号",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "広島県広島市安佐北区口田南四丁目21-7",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "広島県",
				FieldCounty:       nil,
				FieldCity:         "広島市",
				FieldWard:         "安佐北区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "口田南",
				FieldChome:        "四丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "21",
				FieldRsdtNum:      "7",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue78-3a [東京都港区三田２－２－１８三田マンション３０４]",
			query: model.MatchQuery{
				Address:  "東京都港区三田２－２－１８三田マンション３０４",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "東京都港区三田2丁目2",
			wantUnmatchedAddress: []string{"-18", "三田マンション304"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "港区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "三田",
				FieldChome:        "2丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "2",
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue78-3b [東京都港区三田二丁目２番１８−３０４号]",
			query: model.MatchQuery{
				Address:  "東京都港区三田二丁目２番１８−３０４号",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "東京都港区三田2丁目2",
			wantUnmatchedAddress: []string{"-18-304"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "港区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "三田",
				FieldChome:        "2丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "2",
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
	})
}
