package issues

import (
	"abrg/internal/model"
	"testing"
)

// TestIssue131 tests normalization of various dash characters
// Issue131: 二分ダッシュへの対応
// Related: Issue44 番地・号の区切りハイフンの揺らぎ対応検証
func TestIssue131(t *testing.T) {
	runNormalizeTests(t, []normalizeTestCase{
		{
			name: "issue131-1 [東京都千代田区紀尾井町1－3]",
			query: model.MatchQuery{
				Address:  "東京都千代田区紀尾井町1－3",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都千代田区紀尾井町1-3",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "千代田区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "紀尾井町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       "1",
				FieldRsdtNum:      "3",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue131-2 [東京都千代田区紀尾井町1–3]",
			query: model.MatchQuery{
				Address:  "東京都千代田区紀尾井町1–3",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都千代田区紀尾井町1-3",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "千代田区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "紀尾井町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       "1",
				FieldRsdtNum:      "3",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue131-3 [東京都千代田区紀尾井町1—3]",
			query: model.MatchQuery{
				Address:  "東京都千代田区紀尾井町1—3",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都千代田区紀尾井町1-3",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "千代田区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "紀尾井町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       "1",
				FieldRsdtNum:      "3",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue131-4 [東京都千代田区紀尾井町1ー3]",
			query: model.MatchQuery{
				Address:  "東京都千代田区紀尾井町1ー3",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都千代田区紀尾井町1-3",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "千代田区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "紀尾井町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       "1",
				FieldRsdtNum:      "3",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue131-5 [東京都千代田区紀尾井町1ｰ3]",
			query: model.MatchQuery{
				Address:  "東京都千代田区紀尾井町1ｰ3",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都千代田区紀尾井町1-3",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "千代田区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "紀尾井町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       "1",
				FieldRsdtNum:      "3",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
	})
}
