package issues

import (
	"abrg/internal/model"
	"testing"
)

// TestIssue15 tests addresses with repeated city/town names
// Issue #15: 繰り返しの市区町村名・町名
func TestIssue15(t *testing.T) {
	runNormalizeTests(t, []normalizeTestCase{
		// 志布志の繰り返し地名 - 本庁・志布志支所
		{
			name: "issue15-1a [鹿児島県志布志市志布志町志布志二丁目1番1号 本庁・志布志支所]",
			query: model.MatchQuery{
				Address:  "鹿児島県志布志市志布志町志布志二丁目1番1号 本庁・志布志支所",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "鹿児島県志布志市志布志町志布志二丁目1",
			wantUnmatchedAddress: []string{"-1", "本庁・志布志支所"},
			wantStructured: map[string]any{
				FieldPref:         "鹿児島県",
				FieldCounty:       nil,
				FieldCity:         "志布志市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "志布志町志布志",
				FieldChome:        "二丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "1",
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 志布志の繰り返し地名 - 有明支所
		{
			name: "issue15-1b [鹿児島県志布志市有明町野井倉1756番地 有明支所]",
			query: model.MatchQuery{
				Address:  "鹿児島県志布志市有明町野井倉1756番地 有明支所",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "鹿児島県志布志市有明町野井倉1756",
			wantUnmatchedAddress: []string{"有明支所"},
			wantStructured: map[string]any{
				FieldPref:         "鹿児島県",
				FieldCounty:       nil,
				FieldCity:         "志布志市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "有明町野井倉",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      "1756",
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 志布志の繰り返し地名 - 松山支所
		{
			name: "issue15-1c [鹿児島県志布志市松山町新橋268番地 松山支所]",
			query: model.MatchQuery{
				Address:  "鹿児島県志布志市松山町新橋268番地 松山支所",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "鹿児島県志布志市松山町新橋268",
			wantUnmatchedAddress: []string{"松山支所"},
			wantStructured: map[string]any{
				FieldPref:         "鹿児島県",
				FieldCounty:       nil,
				FieldCity:         "志布志市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "松山町新橋",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      "268",
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 京都の通り名を含む繰り返し地名
		{
			name: "issue15-2 [京都府京都市東山区大和大路通正面下る大和大路2]",
			query: model.MatchQuery{
				Address:  "京都府京都市東山区大和大路通正面下る大和大路2",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "京都府京都市東山区大和大路通正面下る大和大路二丁目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "京都府",
				FieldCounty:       nil,
				FieldCity:         "京都市",
				FieldWard:         "東山区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      "大和大路通正面下る",
				FieldOazaCho:      "大和大路二丁目",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 舞浜 - ハイフン表記の曖昧性
		// category rsdtdsp
		{
			name: "issue15-3a [千葉県浦安市舞浜2-11]",
			query: model.MatchQuery{
				Address:  "千葉県浦安市舞浜2-11",
				Category: model.CategoryResidential,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "千葉県浦安市舞浜2丁目11",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "千葉県",
				FieldCounty:       nil,
				FieldCity:         "浦安市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "舞浜",
				FieldChome:        "2丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "11",
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// category parcel
		{
			name: "issue15-3b [千葉県浦安市舞浜2-11]",
			query: model.MatchQuery{
				Address:  "千葉県浦安市舞浜2-11",
				Category: model.CategoryParcel,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "千葉県浦安市舞浜2-11",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "千葉県",
				FieldCounty:       nil,
				FieldCity:         "浦安市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "舞浜",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      "2",
				FieldPrcNum2:      "11",
				FieldPrcNum3:      nil,
			},
		},
		// category allのときはrasdtdsp優先
		{
			name: "issue15-3c [千葉県浦安市舞浜2-11]",
			query: model.MatchQuery{
				Address:  "千葉県浦安市舞浜2-11",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "千葉県浦安市舞浜2丁目11",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "千葉県",
				FieldCounty:       nil,
				FieldCity:         "浦安市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "舞浜",
				FieldChome:        "2丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "11",
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 明示的な住居表示
		{
			name: "issue15-3d [千葉県浦安市舞浜2丁目11番]",
			query: model.MatchQuery{
				Address:  "千葉県浦安市舞浜2丁目11番",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "千葉県浦安市舞浜2丁目11",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "千葉県",
				FieldCounty:       nil,
				FieldCity:         "浦安市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "舞浜",
				FieldChome:        "2丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "11",
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 明示的な地番
		{
			name: "issue15-3e [千葉県浦安市舞浜2番地11]",
			query: model.MatchQuery{
				Address:  "千葉県浦安市舞浜2番地11",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "千葉県浦安市舞浜2-11",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "千葉県",
				FieldCounty:       nil,
				FieldCity:         "浦安市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "舞浜",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      "2",
				FieldPrcNum2:      "11",
				FieldPrcNum3:      nil,
			},
		},
		// 下田市 - 町字に丁目
		{
			name: "issue15-4a [静岡県下田市２ー４ー２６ 下田郵便局]",
			query: model.MatchQuery{
				Address:  "静岡県下田市２ー４ー２６ 下田郵便局",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "静岡県下田市二丁目",
			wantUnmatchedAddress: []string{"4-26", "下田郵便局"},
			wantStructured: map[string]any{
				FieldPref:         "静岡県",
				FieldCounty:       nil,
				FieldCity:         "下田市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "二丁目",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue15-4b [静岡県下田市二丁目４−２６ 下田郵便局]",
			query: model.MatchQuery{
				Address:  "静岡県下田市二丁目４−２６ 下田郵便局",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "静岡県下田市二丁目",
			wantUnmatchedAddress: []string{"4-26", "下田郵便局"},
			wantStructured: map[string]any{
				FieldPref:         "静岡県",
				FieldCounty:       nil,
				FieldCity:         "下田市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "二丁目",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 御所市 - 御所市の直下に地番、1−3のデータは存在しないので期待通り
		{
			name: "issue15-5 [奈良県御所市1番地の3 御所市役所]",
			query: model.MatchQuery{
				Address:  "奈良県御所市1番地の3 御所市役所",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "奈良県御所市",
			wantUnmatchedAddress: []string{"1-3", "御所市役所"},
			wantStructured: map[string]any{
				FieldPref:         "奈良県",
				FieldCounty:       nil,
				FieldCity:         "御所市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      nil,
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 大阪市中央区久太郎町 - 漢字街区符号 (渡辺)
		{
			name: "issue15-6a [大阪市中央区久太郎町4丁目渡辺]",
			query: model.MatchQuery{
				Address:  "大阪市中央区久太郎町4丁目渡辺",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "大阪府大阪市中央区久太郎町4丁目渡辺",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "大阪府",
				FieldCounty:       nil,
				FieldCity:         "大阪市",
				FieldWard:         "中央区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "久太郎町",
				FieldChome:        "4丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "渡辺",
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue15-6b [大阪市中央区久太郎町4丁目渡辺3号]",
			query: model.MatchQuery{
				Address:  "大阪市中央区久太郎町4丁目渡辺3号",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "大阪府大阪市中央区久太郎町4丁目渡辺-3",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "大阪府",
				FieldCounty:       nil,
				FieldCity:         "大阪市",
				FieldWard:         "中央区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "久太郎町",
				FieldChome:        "4丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "渡辺",
				FieldRsdtNum:      "3",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 大阪市中央区上町 - 英字街区符号
		{
			name: "issue15-7a [大阪市中央区上町A-12 独立行政法人　水資源機構　関西・吉野川支社淀川本部]",
			query: model.MatchQuery{
				Address:  "大阪市中央区上町A-12 独立行政法人　水資源機構　関西・吉野川支社淀川本部",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "大阪府大阪市中央区上町A-12",
			wantUnmatchedAddress: []string{"独立行政法人", "水資源機構", "関西・吉野川支社淀川本部"},
			wantStructured: map[string]any{
				FieldPref:         "大阪府",
				FieldCounty:       nil,
				FieldCity:         "大阪市",
				FieldWard:         "中央区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "上町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       "A",
				FieldRsdtNum:      "12",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue15-7b [大阪市中央区上町A-20]",
			query: model.MatchQuery{
				Address:  "大阪府大阪市中央区上町A-20",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "大阪府大阪市中央区上町A-20",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "大阪府",
				FieldCounty:       nil,
				FieldCity:         "大阪市",
				FieldWard:         "中央区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "上町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       "A",
				FieldRsdtNum:      "20",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue15-8 [千葉県八街市八街は１８番地２八街市立八街北中学校]",
			query: model.MatchQuery{
				Address:  "千葉県八街市八街は１８番地２八街市立八街北中学校",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "千葉県八街市八街は",
			wantUnmatchedAddress: []string{"18-2", "八街市立八街北中学校"},
			wantStructured: map[string]any{
				FieldPref:         "千葉県",
				FieldCounty:       nil,
				FieldCity:         "八街市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "八街は",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 長野県長野市南長野県町 - 県名・市名・町名に重複がある。
		// 字県町に地番は無く、477-1 は基底の大字南長野のもの (issue #361)
		{
			name: "issue15-9a [長野県長野市大字南長野県町477-1]",
			query: model.MatchQuery{
				Address:  "長野県長野市大字南長野県町477-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "長野県長野市大字南長野県町",
			wantUnmatchedAddress: []string{"477-1"},
			wantStructured: map[string]any{
				FieldPref:         "長野県",
				FieldCounty:       nil,
				FieldCity:         "長野市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "大字南長野",
				FieldChome:        nil,
				FieldKoaza:        "県町",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue15-9b [長野県長野市南長野県町477-1]",
			query: model.MatchQuery{
				Address:  "長野県長野市南長野県町477-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "長野県長野市大字南長野県町",
			wantUnmatchedAddress: []string{"477-1"},
			wantStructured: map[string]any{
				FieldPref:         "長野県",
				FieldCounty:       nil,
				FieldCity:         "長野市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "大字南長野",
				FieldChome:        nil,
				FieldKoaza:        "県町",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 倉敷市児島下の町 - カタカナ住居番号
		{
			name: "issue15-10 [倉敷市児島下ノ町9丁目12-エ-46]",
			query: model.MatchQuery{
				Address:  "岡山県倉敷市児島下ノ町9丁目12-エ-46",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "岡山県倉敷市児島下の町9丁目12-エ-46",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "岡山県",
				FieldCounty:       nil,
				FieldCity:         "倉敷市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "児島下の町",
				FieldChome:        "9丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "12",
				FieldRsdtNum:      "エ",
				FieldRsdtNum2:     "46",
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
	})
}
