package issues

import (
	"abrg/internal/model"
	"testing"
)

// TestIssue204 tests address normalization where "町" is incorrectly omitted
// Issue #204: 「町」が省略されてしまう問題
// https://github.com/digital-go-jp/abr-geocoder/issues/204
func TestIssue204(t *testing.T) {
	runNormalizeTests(t, []normalizeTestCase{
		// === 長野県長野市 ===
		// 北条町 - 「町」が省略されないこと
		{
			name: "issue204-1 [長野県長野市北条町11]",
			query: model.MatchQuery{
				Address:  "長野県長野市北条町11",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "長野県長野市北条町",
			wantUnmatchedAddress: []string{"11"},
			wantStructured: map[string]any{
				FieldPref:         "長野県",
				FieldCounty:       nil,
				FieldCity:         "長野市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "北条町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// === 愛知県名古屋市 ===
		// 本星崎町 - 「町」が省略されないこと
		{
			name: "issue204-2 [愛知県名古屋市南区本星崎町454]",
			query: model.MatchQuery{
				Address:  "愛知県名古屋市南区本星崎町454",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "愛知県名古屋市南区本星崎町",
			wantUnmatchedAddress: []string{"454"},
			wantStructured: map[string]any{
				FieldPref:         "愛知県",
				FieldCounty:       nil,
				FieldCity:         "名古屋市",
				FieldWard:         "南区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "本星崎町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 笹原町 - 「町」が省略されないこと
		{
			name: "issue204-3 [愛知県名古屋市天白区笹原町1007]",
			query: model.MatchQuery{
				Address:  "愛知県名古屋市天白区笹原町1007",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "愛知県名古屋市天白区笹原町",
			wantUnmatchedAddress: []string{"1007"},
			wantStructured: map[string]any{
				FieldPref:         "愛知県",
				FieldCounty:       nil,
				FieldCity:         "名古屋市",
				FieldWard:         "天白区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "笹原町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// === 島根県出雲市 ===
		// 三津町 - 「町」が省略されないこと
		{
			name: "issue204-4 [島根県出雲市三津町1076]",
			query: model.MatchQuery{
				Address:  "島根県出雲市三津町1076",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "島根県出雲市三津町",
			wantUnmatchedAddress: []string{"1076"},
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "三津町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 塩津町 - 「町」が省略されないこと
		{
			name: "issue204-5 [島根県出雲市塩津町512]",
			query: model.MatchQuery{
				Address:  "島根県出雲市塩津町512",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "島根県出雲市塩津町",
			wantUnmatchedAddress: []string{"512"},
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "塩津町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 天神町 - 「町」が省略されないこと
		{
			name: "issue204-6 [島根県出雲市天神町10]",
			query: model.MatchQuery{
				Address:  "島根県出雲市天神町10",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "島根県出雲市天神町",
			wantUnmatchedAddress: []string{"10"},
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "天神町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 天神町20 - 地番20が存在するためparcelレベルでマッチ
		{
			name: "issue204-6a [島根県出雲市天神町20]",
			query: model.MatchQuery{
				Address:  "島根県出雲市天神町20",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "島根県出雲市天神町20",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "天神町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      "20",
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 浜町 - 「町」が省略されないこと
		{
			name: "issue204-7 [島根県出雲市浜町102]",
			query: model.MatchQuery{
				Address:  "島根県出雲市浜町102",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "島根県出雲市浜町",
			wantUnmatchedAddress: []string{"102"},
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "浜町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 別所町
		{
			name: "issue204-12 [島根県出雲市別所町105]",
			query: model.MatchQuery{
				Address:  "島根県出雲市別所町105",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "島根県出雲市別所町",
			wantUnmatchedAddress: []string{"105"},
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "別所町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 十六島町
		{
			name: "issue204-13 [島根県出雲市十六島町515]",
			query: model.MatchQuery{
				Address:  "島根県出雲市十六島町515",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "島根県出雲市十六島町",
			wantUnmatchedAddress: []string{"515"},
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "十六島町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 唐川町
		{
			name: "issue204-14 [島根県出雲市唐川町111]",
			query: model.MatchQuery{
				Address:  "島根県出雲市唐川町111",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "島根県出雲市唐川町",
			wantUnmatchedAddress: []string{"111"},
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "唐川町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 坂浦町
		{
			name: "issue204-15 [島根県出雲市坂浦町26]",
			query: model.MatchQuery{
				Address:  "島根県出雲市坂浦町26",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "島根県出雲市坂浦町",
			wantUnmatchedAddress: []string{"26"},
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "坂浦町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 大島町
		{
			name: "issue204-16 [島根県出雲市大島町1468]",
			query: model.MatchQuery{
				Address:  "島根県出雲市大島町1468",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "島根県出雲市大島町",
			wantUnmatchedAddress: []string{"1468"},
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "大島町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 小伊津町
		{
			name: "issue204-17 [島根県出雲市小伊津町1494]",
			query: model.MatchQuery{
				Address:  "島根県出雲市小伊津町1494",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "島根県出雲市小伊津町",
			wantUnmatchedAddress: []string{"1494"},
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "小伊津町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 小津町
		{
			name: "issue204-18 [島根県出雲市小津町1208]",
			query: model.MatchQuery{
				Address:  "島根県出雲市小津町1208",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "島根県出雲市小津町",
			wantUnmatchedAddress: []string{"1208"},
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "小津町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 平野町
		{
			name: "issue204-19 [島根県出雲市平野町1133]",
			query: model.MatchQuery{
				Address:  "島根県出雲市平野町1133",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "島根県出雲市平野町",
			wantUnmatchedAddress: []string{"1133"},
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "平野町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 朝山町
		{
			name: "issue204-20 [島根県出雲市朝山町1145]",
			query: model.MatchQuery{
				Address:  "島根県出雲市朝山町1145",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "島根県出雲市朝山町",
			wantUnmatchedAddress: []string{"1145"},
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "朝山町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 河下町
		{
			name: "issue204-21 [島根県出雲市河下町1045]",
			query: model.MatchQuery{
				Address:  "島根県出雲市河下町1045",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "島根県出雲市河下町",
			wantUnmatchedAddress: []string{"1045"},
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "河下町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 渡橋町
		{
			name: "issue204-22 [島根県出雲市渡橋町1032]",
			query: model.MatchQuery{
				Address:  "島根県出雲市渡橋町1032",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "島根県出雲市渡橋町",
			wantUnmatchedAddress: []string{"1032"},
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "渡橋町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 西谷町
		{
			name: "issue204-23 [島根県出雲市西谷町540]",
			query: model.MatchQuery{
				Address:  "島根県出雲市西谷町540",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "島根県出雲市西谷町",
			wantUnmatchedAddress: []string{"540"},
			wantStructured: map[string]any{
				FieldPref:         "島根県",
				FieldCounty:       nil,
				FieldCity:         "出雲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "西谷町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// === 香川県高松市 ===
		// 下田井町 - 「町」が省略されないこと
		{
			name: "issue204-8 [香川県高松市下田井町100]",
			query: model.MatchQuery{
				Address:  "香川県高松市下田井町100",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "香川県高松市下田井町",
			wantUnmatchedAddress: []string{"100"},
			wantStructured: map[string]any{
				FieldPref:         "香川県",
				FieldCounty:       nil,
				FieldCity:         "高松市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "下田井町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 出作町 - 「町」が省略されないこと
		{
			name: "issue204-9 [香川県高松市出作町158]",
			query: model.MatchQuery{
				Address:  "香川県高松市出作町158",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "香川県高松市出作町",
			wantUnmatchedAddress: []string{"158"},
			wantStructured: map[string]any{
				FieldPref:         "香川県",
				FieldCounty:       nil,
				FieldCity:         "高松市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "出作町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 成合町 - 「町」が省略されないこと
		{
			name: "issue204-10 [香川県高松市成合町1098]",
			query: model.MatchQuery{
				Address:  "香川県高松市成合町1098",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "香川県高松市成合町",
			wantUnmatchedAddress: []string{"1098"},
			wantStructured: map[string]any{
				FieldPref:         "香川県",
				FieldCounty:       nil,
				FieldCity:         "高松市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "成合町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 春日町 - 「町」が省略されないこと
		{
			name: "issue204-11 [香川県高松市春日町856]",
			query: model.MatchQuery{
				Address:  "香川県高松市春日町856",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "香川県高松市春日町",
			wantUnmatchedAddress: []string{"856"},
			wantStructured: map[string]any{
				FieldPref:         "香川県",
				FieldCounty:       nil,
				FieldCity:         "高松市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "春日町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 新田町乙 - 「町」が省略されないこと
		{
			name: "issue204-24 [香川県高松市新田町乙11-109]",
			query: model.MatchQuery{
				Address:  "香川県高松市新田町乙11-109",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "香川県高松市新田町乙",
			wantUnmatchedAddress: []string{"11-109"},
			wantStructured: map[string]any{
				FieldPref:         "香川県",
				FieldCounty:       nil,
				FieldCity:         "高松市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "新田町乙",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
	})
}
