package issues

import (
	"abrg/internal/model"
	"testing"
)

// TestIssue202 tests variant character normalization (渕/淵, 篭/籠)
// Issue #202: 「渕」の異体字表記のテスト
func TestIssue202(t *testing.T) {
	runNormalizeTests(t, []normalizeTestCase{
		{
			name: "issue202-1a [石川県加賀市山中温泉枯淵町イ]",
			query: model.MatchQuery{
				Address:  "石川県加賀市山中温泉枯淵町イ",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県加賀市山中温泉枯淵町イ",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "加賀市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "山中温泉枯淵町",
				FieldChome:        nil,
				FieldKoaza:        "イ",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue202-1b [加賀市山中温泉枯淵町ニ乙]",
			query: model.MatchQuery{
				Address:  "石川県加賀市山中温泉枯淵町ニ乙",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県加賀市山中温泉枯淵町ニ乙",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "加賀市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "山中温泉枯淵町",
				FieldChome:        nil,
				FieldKoaza:        "ニ乙",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 枯淵町チ: issue #202で言及
		{
			name: "issue202-1d [石川県加賀市山中温泉枯淵町チ]",
			query: model.MatchQuery{
				Address:  "石川県加賀市山中温泉枯淵町チ",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県加賀市山中温泉枯淵町チ",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "加賀市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "山中温泉枯淵町",
				FieldChome:        nil,
				FieldKoaza:        "チ",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 枯淵町ホ: issue #202で言及
		{
			name: "issue202-1e [石川県加賀市山中温泉枯淵町ホ]",
			query: model.MatchQuery{
				Address:  "石川県加賀市山中温泉枯淵町ホ",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県加賀市山中温泉枯淵町ホ",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "加賀市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "山中温泉枯淵町",
				FieldChome:        nil,
				FieldKoaza:        "ホ",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue202-1c [加賀市山中温泉枯淵町山林ニ乙]",
			query: model.MatchQuery{
				Address:  "石川県加賀市山中温泉枯淵町山林ニ乙",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県加賀市山中温泉枯淵町山林ニ乙",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "加賀市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "山中温泉枯淵町",
				FieldChome:        nil,
				FieldKoaza:        "山林ニ乙",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue202-2a [石川県金沢市水渕町]",
			query: model.MatchQuery{
				Address:  "石川県金沢市水渕町",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "石川県金沢市水淵町",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "金沢市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "水淵町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue202-2b [石川県金沢市水渕町イ]",
			query: model.MatchQuery{
				Address:  "石川県金沢市水渕町イ",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県金沢市水淵町イ",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "金沢市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "水淵町",
				FieldChome:        nil,
				FieldKoaza:        "イ",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "issue202-2c [石川県金沢市水淵町イ]",
			query: model.MatchQuery{
				Address:  "石川県金沢市水淵町イ",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県金沢市水淵町イ",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "金沢市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "水淵町",
				FieldChome:        nil,
				FieldKoaza:        "イ",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// status_flg=0 のためコメントアウト (lg_code=232335, machiaza_id=0259105)
		// {
		// 	name: "issue202-3 [清須市春日渕田]",
		// 	query: model.MatchQuery{
		// 		Address: "愛知県清須市春日渕田",
		// 		Category:  model.CategoryAll,
		// 		Pref: "all",
		// 		Limit:   1,
		// 	},
		// 	wantMatchLevel:       model.MatchLevelMachiazaDetail,
		// 	wantMatchedAddress:   "愛知県清須市春日渕田",
		// 	wantUnmatchedAddress: nil,
		// 	wantStructured: map[string]any{
		// 		FieldPref:     "愛知県",
		// 		FieldCity:     "清須市",
		// 		FieldOazaCho: "春日",
		// 		FieldKoaza:    "渕田",
		// 	},
		// },
		{
			name: "issue202-4 [愛知県西尾市志篭谷町乾地]",
			query: model.MatchQuery{
				Address:  "愛知県西尾市志篭谷町乾地",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "愛知県西尾市志籠谷町乾地",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "愛知県",
				FieldCounty:       nil,
				FieldCity:         "西尾市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "志籠谷町",
				FieldChome:        nil,
				FieldKoaza:        "乾地",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
	})
}
