package issues

import (
	"abrg/internal/model"
	"testing"
)

// TestIssue0 tests basic normalize functionality
// Basic normalize test cases (non-issue specific)
func TestIssue0(t *testing.T) {
	runNormalizeTests(t, []normalizeTestCase{
		// Basic tests
		{
			name: "basic level - chome match",
			query: model.MatchQuery{
				Address:  "大阪府大阪市北区本庄東2丁目",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "大阪府大阪市北区本庄東2丁目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "大阪府",
				FieldCounty:       nil,
				FieldCity:         "大阪市",
				FieldWard:         "北区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "本庄東",
				FieldChome:        "2丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "basic level - with numbers",
			query: model.MatchQuery{
				Address:  "大阪府大阪市北区本庄東2-3-31",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "大阪府大阪市北区本庄東2丁目",
			wantUnmatchedAddress: []string{"3-31"},
			wantStructured: map[string]any{
				FieldPref:         "大阪府",
				FieldCounty:       nil,
				FieldCity:         "大阪市",
				FieldWard:         "北区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "本庄東",
				FieldChome:        "2丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// Residential tests
		{
			name: "residential - ban-go pattern",
			query: model.MatchQuery{
				Address:  "東京都中央区勝どき五丁目12番4号",
				Category: model.CategoryResidential,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都中央区勝どき5丁目12-4",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "勝どき",
				FieldChome:        "5丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "12",
				FieldRsdtNum:      "4",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// Residential vs Parcel priority tests
		{
			name: "ハイフン表記 - 住居表示優先 (category=all)",
			query: model.MatchQuery{
				Address:  "大阪府大阪市北区本庄東2丁目3-31",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "大阪府大阪市北区本庄東2丁目3-31",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "大阪府",
				FieldCounty:       nil,
				FieldCity:         "大阪市",
				FieldWard:         "北区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "本庄東",
				FieldChome:        "2丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "3",
				FieldRsdtNum:      "31",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "街区のみ - 部分マッチ許可 (category=rsdtdsp)",
			query: model.MatchQuery{
				Address:  "大阪府大阪市北区本庄東2丁目3番",
				Category: model.CategoryResidential,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "大阪府大阪市北区本庄東2丁目3",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "大阪府",
				FieldCounty:       nil,
				FieldCity:         "大阪市",
				FieldWard:         "北区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "本庄東",
				FieldChome:        "2丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "3",
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "街区+住居番号 - 完全マッチ (category=rsdtdsp)",
			query: model.MatchQuery{
				Address:  "大阪府大阪市北区本庄東2丁目3番31号",
				Category: model.CategoryResidential,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "大阪府大阪市北区本庄東2丁目3-31",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "大阪府",
				FieldCounty:       nil,
				FieldCity:         "大阪市",
				FieldWard:         "北区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "本庄東",
				FieldChome:        "2丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "3",
				FieldRsdtNum:      "31",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// Chome matching tests
		{
			// 丁目なし - 前方一致検索により市区レベルでマッチ
			name: "丁目なし - 丁目付き結果にマッチしない",
			query: model.MatchQuery{
				Address:  "東京都中央区東日本橋",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelCity,
			wantMatchedAddress:   "東京都中央区",
			wantUnmatchedAddress: []string{"東日本橋"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      nil,
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "丁目あり - 正しくマッチ",
			query: model.MatchQuery{
				Address:  "東京都中央区東日本橋1丁目",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "東京都中央区東日本橋1丁目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "東日本橋",
				FieldChome:        "1丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// Trailing hyphen tests
		{
			name: "末尾ハイフン - 丁目として解釈",
			query: model.MatchQuery{
				Address:  "東京都文京区大塚1-",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "東京都文京区大塚1丁目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "文京区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "大塚",
				FieldChome:        "1丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "ハイフン+0 - 丁目として解釈",
			query: model.MatchQuery{
				Address:  "東京都文京区大塚1-0",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "東京都文京区大塚1丁目",
			wantUnmatchedAddress: []string{"0"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "文京区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "大塚",
				FieldChome:        "1丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "完全な住所 - 正しくマッチ",
			query: model.MatchQuery{
				Address:  "東京都文京区大塚５−１８−５−８０２",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都文京区大塚5丁目18-5",
			wantUnmatchedAddress: []string{"-802"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "文京区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "大塚",
				FieldChome:        "5丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "18",
				FieldRsdtNum:      "5",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// Character normalization tests - 霞ヶ関 vs 霞が関
		// Both should normalize to the same result after NFKC normalization
		{
			name: "霞ヶ関(小書きヶ) - should match 霞が関 after normalization",
			query: model.MatchQuery{
				Address:  "東京都千代田区霞ヶ関1-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "東京都千代田区霞が関一丁目1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "千代田区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "霞が関",
				FieldChome:        "一丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "1",
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "霞が関(ひらがなが) - should match same as 霞ヶ関",
			query: model.MatchQuery{
				Address:  "東京都千代田区霞が関1-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "東京都千代田区霞が関一丁目1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "千代田区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "霞が関",
				FieldChome:        "一丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "1",
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "霞ガ関(大書きガ) - should match same as 霞ヶ関",
			query: model.MatchQuery{
				Address:  "東京都千代田区霞ガ関1-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "東京都千代田区霞が関一丁目1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "千代田区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "霞が関",
				FieldChome:        "一丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "1",
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		{
			name: "有楽町二丁目２番地 - 丁目までマッチ、番地は未マッチ(ハイフンなし)",
			query: model.MatchQuery{
				Address:  "東京都千代田区有楽町二丁目２番地",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "東京都千代田区有楽町二丁目",
			wantUnmatchedAddress: []string{"2"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "千代田区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "有楽町",
				FieldChome:        "二丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		{
			name: "入舟三丁目４番１号宮川工業所 - 住居番号と建物名が分割",
			query: model.MatchQuery{
				Address:  "東京都中央区入舟三丁目４番１号宮川工業所",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "東京都中央区入船3丁目",
			wantUnmatchedAddress: []string{"4-1", "宮川工業所"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "入船",
				FieldChome:        "3丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			// Fixed: chome=二丁目 correctly extracted from "2"
			// Parcel "1" alone doesn't exist in DB (only 1-1, 1-2, etc.), so falls back to chome level
			name: "神田佐久間町２−１ - 丁目までマッチ（地番1単独はDBにない）",
			query: model.MatchQuery{
				Address:  "東京都千代田区神田佐久間町２−１永島ビル９階",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "東京都千代田区神田佐久間町二丁目",
			wantUnmatchedAddress: []string{"1", "永島ビル9階"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "千代田区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "神田佐久間町",
				FieldChome:        "二丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "日本橋人形町三丁目７−１３−２０５ - 住居番号までマッチ、部屋番号のみ未マッチ",
			query: model.MatchQuery{
				Address:  "東京都中央区日本橋人形町三丁目７−１３−２０５",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都中央区日本橋人形町3丁目7-13",
			wantUnmatchedAddress: []string{"-205"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "日本橋人形町",
				FieldChome:        "3丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "7",
				FieldRsdtNum:      "13",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "佃二丁目１０番９−２１０６号 - 住居番号までマッチ、部屋番号のみ未マッチ",
			query: model.MatchQuery{
				Address:  "東京都中央区佃二丁目１０番９−２１０６号",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都中央区佃2丁目10-9",
			wantUnmatchedAddress: []string{"-2106"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "佃",
				FieldChome:        "2丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "10",
				FieldRsdtNum:      "9",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "勝どき五丁目３番１−４２０９号 - 住居番号までマッチ、部屋番号のみ未マッチ",
			query: model.MatchQuery{
				Address:  "東京都中央区勝どき五丁目３番１−４２０９号",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都中央区勝どき5丁目3-1",
			wantUnmatchedAddress: []string{"-4209"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "勝どき",
				FieldChome:        "5丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "3",
				FieldRsdtNum:      "1",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "新川二丁目１３番１１−８０１ - 住居番号までマッチ、部屋番号のみ未マッチ",
			query: model.MatchQuery{
				Address:  "東京都中央区新川二丁目１３番１１−８０１",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都中央区新川2丁目13-11",
			wantUnmatchedAddress: []string{"-801"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "新川",
				FieldChome:        "2丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "13",
				FieldRsdtNum:      "11",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "文京区本郷二丁目109番地1の9 - 地番3桁完全マッチ(prc_num1-prc_num2-prc_num3)",
			query: model.MatchQuery{
				Address:  "文京区本郷二丁目109番地1の9",
				Category: model.CategoryParcel,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "東京都文京区本郷2丁目109-1-9",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "文京区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "本郷",
				FieldChome:        "2丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      "109",
				FieldPrcNum2:      "1",
				FieldPrcNum3:      "9",
			},
		},
		{
			name: "岐阜県中津川市駒場１６６６番地の３４３７ - 地番2桁完全マッチ(大きい桁数)",
			query: model.MatchQuery{
				Address:  "岐阜県中津川市駒場１６６６番地の３４３７",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "岐阜県中津川市駒場1666-3437",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "岐阜県",
				FieldCounty:       nil,
				FieldCity:         "中津川市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "駒場",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      "1666",
				FieldPrcNum2:      "3437",
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "西神田三丁目５番３−２４１４号 - 漢数字の丁目、街区までマッチ（住居番号3は三丁目に存在しない）",
			query: model.MatchQuery{
				Address:  "東京都千代田区西神田三丁目５番３−２４１４号",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "東京都千代田区西神田三丁目5",
			wantUnmatchedAddress: []string{"-3-2414"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "千代田区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "西神田",
				FieldChome:        "三丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "5",
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// Special cases - Non-numeric block/residential numbers
		{
			name: "米沢市福田町2丁目3-156-9 - 数値rsdt_num2",
			query: model.MatchQuery{
				Address:  "山形県米沢市福田町2丁目3-156-9",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "山形県米沢市福田町2丁目3-156-9",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "山形県",
				FieldCounty:       nil,
				FieldCity:         "米沢市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "福田町",
				FieldChome:        "2丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "3",
				FieldRsdtNum:      "156",
				FieldRsdtNum2:     "9",
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "鶴岡市新形町7-20-9 - 丁目なし数値rsdt_num2",
			query: model.MatchQuery{
				Address:  "山形県鶴岡市新形町7-20-9",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "山形県鶴岡市新形町7-20-9",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "山形県",
				FieldCounty:       nil,
				FieldCity:         "鶴岡市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "新形町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       "7",
				FieldRsdtNum:      "20",
				FieldRsdtNum2:     "9",
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "久太郎町四丁目渡辺 - 漢字の街区番号",
			query: model.MatchQuery{
				Address:  "大阪府大阪市中央区久太郎町四丁目渡辺",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "大阪府大阪市中央区久太郎町4丁目渡辺",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "大阪府",
				FieldCounty:       nil,
				FieldCity:         "大阪市",
				FieldWard:         "中央区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "久太郎町",
				FieldChome:        "4丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "渡辺",
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// Test for existing chome - should match to chome level
		{
			name: "神田鍛冶町三丁目 - 丁目レベルまでマッチ",
			query: model.MatchQuery{
				Address:  "東京都千代田区神田鍛冶町三丁目２４番地",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "東京都千代田区神田鍛冶町三丁目",
			wantUnmatchedAddress: []string{"24"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "千代田区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "神田鍛冶町",
				FieldChome:        "三丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// Test for existing parcel - should match to parcel level
		{
			name: "神田鍛冶町三丁目3-1 - 地番レベルまで完全マッチ",
			query: model.MatchQuery{
				Address:  "東京都千代田区神田鍛冶町三丁目３番地１",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "東京都千代田区神田鍛冶町三丁目3-1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "千代田区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "神田鍛冶町",
				FieldChome:        "三丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      "3",
				FieldPrcNum2:      "1",
				FieldPrcNum3:      nil,
			},
		},
		// Test for non-existent chome - should fallback to city level
		{
			name: "存在しない丁目 - 市区レベルにフォールバック",
			query: model.MatchQuery{
				Address:  "東京都千代田区神田鍛冶町二丁目２４番地",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelCity,
			wantMatchedAddress:   "東京都千代田区",
			wantUnmatchedAddress: []string{"神田鍛冶町二丁目24"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "千代田区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      nil,
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// Test for exact chome match in residential address
		{
			name: "築地六丁目 - 丁目が完全一致して住居表示レベルまでマッチ",
			query: model.MatchQuery{
				Address:  "東京都中央区築地六丁目4番5号",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都中央区築地6丁目4-5",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "築地",
				FieldChome:        "6丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "4",
				FieldRsdtNum:      "5",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// N号 (Hokkaido koaza with 号)
		{
			name: "[北海道旭川市西神楽南13号] (N号 should not convert to -N)",
			query: model.MatchQuery{
				Address:  "北海道旭川市西神楽南13号",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "北海道旭川市西神楽南13号",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "北海道",
				FieldCounty:       nil,
				FieldCity:         "旭川市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "西神楽南",
				FieldChome:        nil,
				FieldKoaza:        "13号",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "[北海道釧路市音別町あけぼの1丁目] (アケボノ should not convert to アケボ-)",
			query: model.MatchQuery{
				Address:  "北海道釧路市音別町あけぼの1丁目",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "北海道釧路市音別町あけぼの1丁目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "北海道",
				FieldCounty:       nil,
				FieldCity:         "釧路市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "音別町あけぼの",
				FieldChome:        "1丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "[北海道帯広市岩内町第1基線] (基線 should not get space inserted)",
			query: model.MatchQuery{
				Address:  "北海道帯広市岩内町第1基線",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "北海道帯広市岩内町第1基線",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "北海道",
				FieldCounty:       nil,
				FieldCity:         "帯広市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "岩内町第1基線",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// N番川
		{
			name: "[北海道石狩郡当別町字青山奥2番川] (N番川 should not separate)",
			query: model.MatchQuery{
				Address:  "北海道石狩郡当別町字青山奥2番川",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "北海道石狩郡当別町字青山奥2番川",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "北海道",
				FieldCounty:       "石狩郡",
				FieldCity:         "当別町",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "字青山奥2番川",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// N分区
		{
			name: "[宮城県東松島市宮戸字11分区] (N分区 should not get space inserted)",
			query: model.MatchQuery{
				Address:  "宮城県東松島市宮戸字11分区",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "宮城県東松島市宮戸字11分区",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "宮城県",
				FieldCounty:       nil,
				FieldCity:         "東松島市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "宮戸",
				FieldChome:        nil,
				FieldKoaza:        "字11分区",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// 第N基線北M線
		{
			name: "[北海道阿寒郡鶴居村字幌呂原野第1基線北1線] (基線北 should match)",
			query: model.MatchQuery{
				Address:  "北海道阿寒郡鶴居村字幌呂原野第1基線北1線",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "北海道阿寒郡鶴居村字幌呂原野第1基線北1線",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "北海道",
				FieldCounty:       "阿寒郡",
				FieldCity:         "鶴居村",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "字幌呂原野第1基線北",
				FieldChome:        nil,
				FieldKoaza:        "1線",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// Nの通り
		{
			name: "[北海道厚岸郡厚岸町太田1の通り] (Nの通り should not get space inserted)",
			query: model.MatchQuery{
				Address:  "北海道厚岸郡厚岸町太田1の通り",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "北海道厚岸郡厚岸町太田1の通り",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "北海道",
				FieldCounty:       "厚岸郡",
				FieldCity:         "厚岸町",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "太田1の通り",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// N町内会
		{
			name: "[北海道深川市音江町字国見14町内会] (N町内会 should not get space inserted)",
			query: model.MatchQuery{
				Address:  "北海道深川市音江町字国見14町内会",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "北海道深川市音江町字国見14町内会",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "北海道",
				FieldCounty:       nil,
				FieldCity:         "深川市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "音江町",
				FieldChome:        nil,
				FieldKoaza:        "字国見14町内会",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// N番通
		{
			name: "[北海道上川郡東神楽町南1番通] (N番通 should not separate)",
			query: model.MatchQuery{
				Address:  "北海道上川郡東神楽町南1番通",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "北海道上川郡東神楽町南1番通",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "北海道",
				FieldCounty:       "上川郡",
				FieldCity:         "東神楽町",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "南1番通",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// N字 (Ishikawa-style koaza)
		{
			name: "[石川県羽咋市飯山町1字] (N字 should not get space inserted)",
			query: model.MatchQuery{
				Address:  "石川県羽咋市飯山町1字",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県羽咋市飯山町1字",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "羽咋市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "飯山町",
				FieldChome:        nil,
				FieldKoaza:        "1字",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// N丁 (Osaka-style chome without 目)
		{
			name: "[大阪府堺市南区庭代台4丁] (N丁 should not get space inserted)",
			query: model.MatchQuery{
				Address:  "大阪府堺市南区庭代台4丁",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "大阪府堺市南区庭代台4丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "大阪府",
				FieldCounty:       nil,
				FieldCity:         "堺市",
				FieldWard:         "南区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "庭代台",
				FieldChome:        "4丁",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// NノM町 (Niigata-style town addresses)
		// Note: This address has no chome or koaza in DB, so it matches at machiaza level
		{
			name: "[新潟県新潟市中央区礎町通1ノ町] (NノM町 should not be converted to N-M町)",
			query: model.MatchQuery{
				Address:  "新潟県新潟市中央区礎町通1ノ町",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "新潟県新潟市中央区礎町通1ノ町",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "新潟県",
				FieldCounty:       nil,
				FieldCity:         "新潟市",
				FieldWard:         "中央区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "礎町通1ノ町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// Nの町
		{
			name: "[新潟県新潟市西区五十嵐1の町] (Nの町 should not get space inserted)",
			query: model.MatchQuery{
				Address:  "新潟県新潟市西区五十嵐1の町",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "新潟県新潟市西区五十嵐1の町",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "新潟県",
				FieldCounty:       nil,
				FieldCity:         "新潟市",
				FieldWard:         "西区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "五十嵐1の町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// Nの at end of address (Ishikawa-style koaza)
		{
			name: "[石川県金沢市天池町1の] (Nの at end should not be separated)",
			query: model.MatchQuery{
				Address:  "石川県金沢市天池町1の",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県金沢市天池町1の",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "金沢市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "天池町",
				FieldChome:        nil,
				FieldKoaza:        "1の",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// 字N-M街区 (Fukushima-style koaza with block number)
		{
			name: "[福島県喜多方市塩川町字11-2街区] (字N-M街区 should match)",
			query: model.MatchQuery{
				Address:  "福島県喜多方市塩川町字11-2街区",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "福島県喜多方市塩川町字11-2街区",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "福島県",
				FieldCounty:       nil,
				FieldCity:         "喜多方市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "塩川町",
				FieldChome:        nil,
				FieldKoaza:        "字11-2街区",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// N部 (Ishikawa-style section addresses)
		{
			name: "[石川県輪島市市ノ瀬町15部] (N部 should not get space inserted)",
			query: model.MatchQuery{
				Address:  "石川県輪島市市ノ瀬町15部",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県輪島市市ノ瀬町15部",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "輪島市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "市ノ瀬町",
				FieldChome:        nil,
				FieldKoaza:        "15部",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// N番丁 (Kanazawa-style town addresses)
		{
			name: "[石川県金沢市池田町1番丁] (N番丁 should not get space inserted)",
			query: model.MatchQuery{
				Address:  "石川県金沢市池田町1番丁",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "石川県金沢市池田町1番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "金沢市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "池田町1番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// 漢字N漢字M丁目 (Hokkaido Nakashibetsu-style)
		// Address format: 漢字+数字+漢字+数字+丁目 (e.g., 東1北2丁目)
		{
			name: "[北海道標津郡中標津町東1北2丁目] (東N北M should match)",
			query: model.MatchQuery{
				Address:  "北海道標津郡中標津町東1北2丁目",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "北海道標津郡中標津町東1北2丁目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "北海道",
				FieldCounty:       "標津郡",
				FieldCity:         "中標津町",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "東1北",
				FieldChome:        "2丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// N番内 (Hokkaido koaza with 番内)
		{
			name: "[北海道川上郡標茶町字標茶9813番内] (N番内 should not get space inserted)",
			query: model.MatchQuery{
				Address:  "北海道川上郡標茶町字標茶9813番内",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "北海道川上郡標茶町字標茶9813番内",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "北海道",
				FieldCounty:       "川上郡",
				FieldCity:         "標茶町",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "字標茶",
				FieldChome:        nil,
				FieldKoaza:        "9813番内",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// N本通 (tree-counting koaza - Hokkaido)
		{
			name: "[北海道川上郡標茶町字虹別市街3本通線] (N本通 should not get space inserted)",
			query: model.MatchQuery{
				Address:  "北海道川上郡標茶町字虹別市街3本通線",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "北海道川上郡標茶町字虹別市街3本通線",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "北海道",
				FieldCounty:       "川上郡",
				FieldCity:         "標茶町",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "字虹別市街",
				FieldChome:        nil,
				FieldKoaza:        "3本通線",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// N本松 (tree-counting koaza - Saga)
		// Note: DB has two entries with same normalized_address but different koaza:
		//   - machiaza_id=0019117: koaza="大1本松" (Arabic numeral from "大１本松" full-width)
		//   - machiaza_id=0019125: koaza="大一本松" (Kanji numeral)
		// Both have normalized_address="神埼市千代田町姉大1本松", result depends on DB order
		{
			name: "[佐賀県神埼市千代田町姉大1本松] (N本松 should not get space inserted)",
			query: model.MatchQuery{
				Address:  "佐賀県神埼市千代田町姉大1本松",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "佐賀県神埼市千代田町姉大1本松",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "佐賀県",
				FieldCounty:       nil,
				FieldCity:         "神埼市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "千代田町姉",
				FieldChome:        nil,
				FieldKoaza:        "大1本松",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "[佐賀県神埼市千代田町姉大一本松] (漢数字入力は漢数字でマッチ)",
			query: model.MatchQuery{
				Address:  "佐賀県神埼市千代田町姉大一本松",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "佐賀県神埼市千代田町姉大一本松",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "佐賀県",
				FieldCounty:       nil,
				FieldCity:         "神埼市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "千代田町姉",
				FieldChome:        nil,
				FieldKoaza:        "大一本松",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// Nの坪/Nノ坪 (field measurement koaza - Saga)
		// Note: DB has two entries with same normalized_address but different koaza:
		//   - machiaza_id=0032136: koaza="8の坪" (Arabic numeral)
		//   - machiaza_id=0032126: koaza="八の坪" (Kanji numeral)
		// Both have normalized_address="神埼市千代田町渡瀬8ノ坪", result depends on DB order
		// Actual result returns "8の坪" (machiaza_id=0032136)
		{
			name: "[佐賀県神埼市千代田町渡瀬8の坪] (Nの坪 should not get space inserted)",
			query: model.MatchQuery{
				Address:  "佐賀県神埼市千代田町渡瀬8の坪",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "佐賀県神埼市千代田町渡瀬8の坪",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "佐賀県",
				FieldCounty:       nil,
				FieldCity:         "神埼市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "千代田町渡瀬",
				FieldChome:        nil,
				FieldKoaza:        "8の坪",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// Kanji numeral input is normalized to Arabic numeral during search
		// DB has two records with same normalized_address but different koaza:
		//   - machiaza_id=0032136: koaza="8の坪" (Arabic numeral)
		//   - machiaza_id=0032126: koaza="八の坪" (Kanji numeral)
		// Input "八の坪" should return "八の坪" (kanji version) because jaccard similarity
		// prefers the DB record that matches original input more closely
		{
			name: "[佐賀県神埼市千代田町渡瀬八の坪] (漢数字入力は漢数字でマッチ)",
			query: model.MatchQuery{
				Address:  "佐賀県神埼市千代田町渡瀬八の坪",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "佐賀県神埼市千代田町渡瀬八の坪", // Returns kanji version matching input
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "佐賀県",
				FieldCounty:       nil,
				FieldCity:         "神埼市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "千代田町渡瀬",
				FieldChome:        nil,
				FieldKoaza:        "八の坪", // Returns kanji version matching input,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// Katakana/Hiragana variants (Ishikawa)
		// DB has two entries with same normalized_address but different koaza:
		//   - machiaza_id=0132140: koaza="ろ" (Hiragana)
		//   - machiaza_id=0132141: koaza="ロ" (Katakana)
		// Input should match the variant that matches original input
		{
			name: "[石川県加賀市深田町ロ] (カタカナ入力はカタカナでマッチ)",
			query: model.MatchQuery{
				Address:  "石川県加賀市深田町ロ",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県加賀市深田町ロ",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "加賀市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "深田町",
				FieldChome:        nil,
				FieldKoaza:        "ロ",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "[石川県加賀市深田町ろ] (ひらがな入力はひらがなでマッチ)",
			query: model.MatchQuery{
				Address:  "石川県加賀市深田町ろ",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県加賀市深田町ろ",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "加賀市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "深田町",
				FieldChome:        nil,
				FieldKoaza:        "ろ",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// Kanji/Arabic numeral + の variants (Ishikawa)
		// DB has two entries:
		//   - machiaza_id=0025187: koaza="6の" (Arabic numeral)
		//   - machiaza_id=0025196: koaza="六の" (Kanji numeral)
		{
			name: "[石川県加賀市熊坂町6の] (アラビア数字入力はアラビア数字でマッチ)",
			query: model.MatchQuery{
				Address:  "石川県加賀市熊坂町6の",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県加賀市熊坂町6の",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "加賀市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "熊坂町",
				FieldChome:        nil,
				FieldKoaza:        "6の",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		{
			name: "[石川県加賀市熊坂町六の] (漢数字入力は漢数字でマッチ)",
			query: model.MatchQuery{
				Address:  "石川県加賀市熊坂町六の",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県加賀市熊坂町六の",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "加賀市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "熊坂町",
				FieldChome:        nil,
				FieldKoaza:        "六の",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// Nケ村入会地 (multi-village communal land - Toyama)
		{
			name: "[富山県南砺市井波外2ケ村入会地] (Nケ村 should not get space inserted)",
			query: model.MatchQuery{
				Address:  "富山県南砺市井波外2ケ村入会地",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "富山県南砺市井波外2ケ村入会地",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "富山県",
				FieldCounty:       nil,
				FieldCity:         "南砺市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "井波外2ケ村入会地",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// Issue : parcel with building name
		{
			name: "[宮城県仙台市青葉区熊ケ根字檀の原一番41-29細川アパート1050]",
			query: model.MatchQuery{
				Address:  "宮城県仙台市青葉区熊ケ根字檀の原一番４１番地の２９細川アパート１０５０",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "宮城県仙台市青葉区熊ケ根字檀の原一番41-29",
			wantUnmatchedAddress: []string{"細川アパート1050"},
			wantStructured: map[string]any{
				FieldPref:         "宮城県",
				FieldCounty:       nil,
				FieldCity:         "仙台市",
				FieldWard:         "青葉区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "熊ケ根",
				FieldChome:        nil,
				FieldKoaza:        "字檀の原一番",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      "41",
				FieldPrcNum2:      "29",
				FieldPrcNum3:      nil,
			},
		},
	})
}
