package issues

import (
	"abrg/internal/model"
	"testing"
)

// TestIssue195 tests place names containing "番丁"
// Issue #195: 「番丁」が省略される
// https://github.com/digital-go-jp/abr-geocoder/issues/195
//
// 問題:
// - 「一番丁」→「一」（「番丁」が脱落）
// - 金沢市、和歌山市、仙台市などに「番丁」を含む地名が多数存在
//
// 「番丁」は地名の一部として正しく保持されるべき
func TestIssue195(t *testing.T) {
	runNormalizeTests(t, []normalizeTestCase{
		// === 金沢市 池田町パターン ===
		// oaza_cho が「池田町N番丁」の形式
		{
			name: "issue195-1 [石川県金沢市池田町一番丁]",
			query: model.MatchQuery{
				Address:  "石川県金沢市池田町一番丁",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "石川県金沢市池田町1番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "金沢市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "池田町1番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// アラビア数字での入力
		{
			name: "issue195-1a [石川県金沢市池田町1番丁]",
			query: model.MatchQuery{
				Address:  "石川県金沢市池田町1番丁",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "石川県金沢市池田町1番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "金沢市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "池田町1番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 池田町2番丁
		{
			name: "issue195-2 [石川県金沢市池田町二番丁]",
			query: model.MatchQuery{
				Address:  "石川県金沢市池田町二番丁",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "石川県金沢市池田町2番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "金沢市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "池田町2番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 池田町3番丁
		{
			name: "issue195-3 [石川県金沢市池田町三番丁]",
			query: model.MatchQuery{
				Address:  "石川県金沢市池田町三番丁",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "石川県金沢市池田町3番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "金沢市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "池田町3番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// 池田町4番丁
		{
			name: "issue195-3a [石川県金沢市池田町四番丁]",
			query: model.MatchQuery{
				Address:  "石川県金沢市池田町四番丁",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "石川県金沢市池田町4番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "金沢市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "池田町4番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// === 金沢市 西町パターン ===
		// 西町3番丁
		{
			name: "issue195-4 [石川県金沢市西町三番丁]",
			query: model.MatchQuery{
				Address:  "石川県金沢市西町三番丁",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "石川県金沢市西町3番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "金沢市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "西町3番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 西町4番丁
		{
			name: "issue195-4a [石川県金沢市西町四番丁]",
			query: model.MatchQuery{
				Address:  "石川県金沢市西町四番丁",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "石川県金沢市西町4番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "金沢市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "西町4番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// === 金沢市 下本多町パターン ===
		// 下本多町5番丁
		{
			name: "issue195-5 [石川県金沢市下本多町五番丁]",
			query: model.MatchQuery{
				Address:  "石川県金沢市下本多町五番丁",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "石川県金沢市下本多町5番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "金沢市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "下本多町5番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 下本多町6番丁
		{
			name: "issue195-5a [石川県金沢市下本多町六番丁]",
			query: model.MatchQuery{
				Address:  "石川県金沢市下本多町六番丁",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "石川県金沢市下本多町6番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "金沢市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "下本多町6番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// === 仙台市 東N番丁パターン ===
		// 「東」+「N番丁」の形式
		// DB: oaza_cho=東七番丁（漢数字）
		{
			name: "issue195-6 [宮城県仙台市若林区東七番丁]",
			query: model.MatchQuery{
				Address:  "宮城県仙台市若林区東七番丁",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "宮城県仙台市若林区東七番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "宮城県",
				FieldCounty:       nil,
				FieldCity:         "仙台市",
				FieldWard:         "若林区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "東七番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 東八番丁
		{
			name: "issue195-7 [宮城県仙台市若林区東八番丁]",
			query: model.MatchQuery{
				Address:  "宮城県仙台市若林区東八番丁",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "宮城県仙台市若林区東八番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "宮城県",
				FieldCounty:       nil,
				FieldCity:         "仙台市",
				FieldWard:         "若林区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "東八番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// === 和歌山市パターン ===
		// oaza_cho が「N番丁」の形式（地名なし）
		// DB: oaza_cho=三番丁（漢数字）
		{
			name: "issue195-8 [和歌山県和歌山市三番丁]",
			query: model.MatchQuery{
				Address:  "和歌山県和歌山市三番丁",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "和歌山県和歌山市三番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "和歌山県",
				FieldCounty:       nil,
				FieldCity:         "和歌山市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "三番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 十番丁（二桁）
		{
			name: "issue195-9 [和歌山県和歌山市十番丁]",
			query: model.MatchQuery{
				Address:  "和歌山県和歌山市十番丁",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "和歌山県和歌山市十番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "和歌山県",
				FieldCounty:       nil,
				FieldCity:         "和歌山市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "十番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 十三番丁
		{
			name: "issue195-10 [和歌山県和歌山市十三番丁]",
			query: model.MatchQuery{
				Address:  "和歌山県和歌山市十三番丁",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "和歌山県和歌山市十三番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "和歌山県",
				FieldCounty:       nil,
				FieldCity:         "和歌山市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "十三番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// === 丸亀市パターン ===
		// DB: oaza_cho=六番丁（漢数字）
		{
			name: "issue195-11 [香川県丸亀市六番丁]",
			query: model.MatchQuery{
				Address:  "香川県丸亀市六番丁",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "香川県丸亀市六番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "香川県",
				FieldCounty:       nil,
				FieldCity:         "丸亀市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "六番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 十番丁
		{
			name: "issue195-12 [香川県丸亀市十番丁]",
			query: model.MatchQuery{
				Address:  "香川県丸亀市十番丁",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "香川県丸亀市十番丁",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "香川県",
				FieldCounty:       nil,
				FieldCity:         "丸亀市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "十番丁",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
	})
}
