package issues

import (
	"abrg/internal/model"
	"testing"
)

// TestIssue199 tests place names containing kanji numerals and circles
// Issue #199: 漢数字が誤って算用数字に変換される問題
// https://github.com/digital-go-jp/abr-geocoder/issues/199
//
// 問題:
// - 「壱〇七」→「壱〇7」（末尾の漢数字が算用数字に変換される）
// - 「壱〇九」→「壱〇9」
// - 「壱〇五」→「壱〇5」
// - 「弐〇四」→「弐〇4」
// - 「壱〇壱部」→「10 壱部」または「壱〇 壱部」（スペースが誤挿入される）
//
// 町字・小字に含まれる漢数字は地名の一部として扱い、算用数字に変換すべきでない
func TestIssue199(t *testing.T) {
	runNormalizeTests(t, []normalizeTestCase{
		// === 珠洲市: 〇を含む小字で末尾に「部」がつくケース ===
		// 弐〇部: 漢数字がそのまま保持されるべき
		{
			name: "issue199-1 [石川県珠洲市三崎町本弐〇部]",
			query: model.MatchQuery{
				Address:  "石川県珠洲市三崎町本弐〇部",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県珠洲市三崎町本弐〇部",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "珠洲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "三崎町本",
				FieldChome:        nil,
				FieldKoaza:        "弐〇部",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 壱〇部: 漢数字がそのまま保持されるべき
		{
			name: "issue199-2 [石川県珠洲市若山町鈴内壱〇部]",
			query: model.MatchQuery{
				Address:  "石川県珠洲市若山町鈴内壱〇部",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県珠洲市若山町鈴内壱〇部",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "珠洲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "若山町鈴内",
				FieldChome:        nil,
				FieldKoaza:        "壱〇部",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 参〇部
		{
			name: "issue199-3 [石川県珠洲市若山町出田参〇部]",
			query: model.MatchQuery{
				Address:  "石川県珠洲市若山町出田参〇部",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県珠洲市若山町出田参〇部",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "珠洲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "若山町出田",
				FieldChome:        nil,
				FieldKoaza:        "参〇部",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 四〇部
		{
			name: "issue199-4 [石川県珠洲市若山町出田四〇部]",
			query: model.MatchQuery{
				Address:  "石川県珠洲市若山町出田四〇部",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県珠洲市若山町出田四〇部",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "珠洲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "若山町出田",
				FieldChome:        nil,
				FieldKoaza:        "四〇部",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// === 珠洲市: 〇を含む小字で末尾に「字」がつくケース ===
		// 壱〇字
		{
			name: "issue199-5 [石川県珠洲市若山町上山壱〇字]",
			query: model.MatchQuery{
				Address:  "石川県珠洲市若山町上山壱〇字",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県珠洲市若山町上山壱〇字",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "珠洲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "若山町上山",
				FieldChome:        nil,
				FieldKoaza:        "壱〇字",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 弐〇字
		{
			name: "issue199-6 [石川県珠洲市若山町上山弐〇字]",
			query: model.MatchQuery{
				Address:  "石川県珠洲市若山町上山弐〇字",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県珠洲市若山町上山弐〇字",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "珠洲市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "若山町上山",
				FieldChome:        nil,
				FieldKoaza:        "弐〇字",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// === 志賀町: 漢数字のみの小字パターン ===
		// Issue #199修正後: 漢数字のみの小字（壱〇, 弐〇など）も正しくmachiaza_detailレベルでマッチ
		// 入力の漢数字は算用数字に変換されるが、DetectMachiazaで小字との照合を行う
		// 壱〇（漢数字のみ）- koazaレベルで完全マッチ
		{
			name: "issue199-7 [石川県羽咋郡志賀町福浦港壱〇]",
			query: model.MatchQuery{
				Address:  "石川県羽咋郡志賀町福浦港壱〇",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県羽咋郡志賀町福浦港壱〇",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       "羽咋郡",
				FieldCity:         "志賀町",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "福浦港",
				FieldChome:        nil,
				FieldKoaza:        "壱〇",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 弐〇 - koazaレベルで完全マッチ
		{
			name: "issue199-8 [石川県羽咋郡志賀町尊保弐〇]",
			query: model.MatchQuery{
				Address:  "石川県羽咋郡志賀町尊保弐〇",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県羽咋郡志賀町尊保弐〇",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       "羽咋郡",
				FieldCity:         "志賀町",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "尊保",
				FieldChome:        nil,
				FieldKoaza:        "弐〇",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 壱参 - koazaレベルで完全マッチ
		{
			name: "issue199-9 [石川県羽咋郡志賀町阿川壱参]",
			query: model.MatchQuery{
				Address:  "石川県羽咋郡志賀町阿川壱参",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県羽咋郡志賀町阿川壱参",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       "羽咋郡",
				FieldCity:         "志賀町",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "阿川",
				FieldChome:        nil,
				FieldKoaza:        "壱参",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 壱七 - koazaレベルで完全マッチ
		{
			name: "issue199-10 [石川県羽咋郡志賀町和田壱七]",
			query: model.MatchQuery{
				Address:  "石川県羽咋郡志賀町和田壱七",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県羽咋郡志賀町和田壱七",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       "羽咋郡",
				FieldCity:         "志賀町",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "和田",
				FieldChome:        nil,
				FieldKoaza:        "壱七",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 弐五 - koazaレベルで完全マッチ
		{
			name: "issue199-11 [石川県羽咋郡志賀町上棚弐五]",
			query: model.MatchQuery{
				Address:  "石川県羽咋郡志賀町上棚弐五",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県羽咋郡志賀町上棚弐五",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       "羽咋郡",
				FieldCity:         "志賀町",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "上棚",
				FieldChome:        nil,
				FieldKoaza:        "弐五",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// === 輪島市: 漢数字入力が算用数字koazaにマッチするケース ===
		// DB: koaza=107（算用数字）, 入力: 壱〇七（漢数字）→ 107 に変換してマッチ
		{
			name: "issue199-12 [石川県輪島市門前町暮坂壱〇七]",
			query: model.MatchQuery{
				Address:  "石川県輪島市門前町暮坂壱〇七",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県輪島市門前町暮坂107",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "輪島市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "門前町暮坂",
				FieldChome:        nil,
				FieldKoaza:        "107",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 壱〇九
		{
			name: "issue199-13 [石川県輪島市門前町暮坂壱〇九]",
			query: model.MatchQuery{
				Address:  "石川県輪島市門前町暮坂壱〇九",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県輪島市門前町暮坂109",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "輪島市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "門前町暮坂",
				FieldChome:        nil,
				FieldKoaza:        "109",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 壱〇五
		{
			name: "issue199-14 [石川県輪島市門前町暮坂壱〇五]",
			query: model.MatchQuery{
				Address:  "石川県輪島市門前町暮坂壱〇五",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県輪島市門前町暮坂105",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "石川県",
				FieldCounty:       nil,
				FieldCity:         "輪島市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "門前町暮坂",
				FieldChome:        nil,
				FieldKoaza:        "105",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
	})
}
