package issues

import (
	"abrg/internal/model"
	"testing"
)

// TestIssue200 tests address normalization for "町目" suffix being dropped
// Issue #200: 町目が省略される問題
// https://github.com/digital-go-jp/abr-geocoder/issues/200
//
// 問題:
// - 「新潟県佐渡市相川一町目」→「新潟県佐渡市相川一」（町目が省略される）
// - 「福島県いわき市平六町目」→「福島県いわき市平六」（町目が省略される）
// - 「新潟県佐渡市相川一町目浜町」→「新潟県佐渡市相川一浜町」（町目が省略される）
//
// 町名の一部として「一町目」「二町目」などの数字+町目パターンがある場合、
// 「町目」が脱落して数字だけが残る問題
func TestIssue200(t *testing.T) {
	runNormalizeTests(t, []normalizeTestCase{
		// === 京都市パターン（既存テスト） ===
		{
			name: "issue200-1a [京都市上京区橋西二町目616-2]",
			query: model.MatchQuery{
				Address:  "京都府京都市上京区橋西二町目616-2",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "京都府京都市上京区橋西二町目616-2",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "京都府",
				FieldCounty:       nil,
				FieldCity:         "京都市",
				FieldWard:         "上京区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "橋西二町目",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      "616",
				FieldPrcNum2:      "2",
				FieldPrcNum3:      nil,
			},
		},

		// === 佐渡市相川パターン ===
		// 相川一町目: 町目が省略されず完全マッチすべき
		{
			name: "issue200-1b [新潟県佐渡市相川一町目]",
			query: model.MatchQuery{
				Address:  "新潟県佐渡市相川一町目",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "新潟県佐渡市相川一町目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "新潟県",
				FieldCounty:       nil,
				FieldCity:         "佐渡市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "相川一町目",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 相川二町目
		{
			name: "issue200-2 [新潟県佐渡市相川二町目]",
			query: model.MatchQuery{
				Address:  "新潟県佐渡市相川二町目",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "新潟県佐渡市相川二町目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "新潟県",
				FieldCounty:       nil,
				FieldCity:         "佐渡市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "相川二町目",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 相川三町目
		{
			name: "issue200-3 [新潟県佐渡市相川三町目]",
			query: model.MatchQuery{
				Address:  "新潟県佐渡市相川三町目",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "新潟県佐渡市相川三町目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "新潟県",
				FieldCounty:       nil,
				FieldCity:         "佐渡市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "相川三町目",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 相川四町目
		{
			name: "issue200-4 [新潟県佐渡市相川四町目]",
			query: model.MatchQuery{
				Address:  "新潟県佐渡市相川四町目",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "新潟県佐渡市相川四町目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "新潟県",
				FieldCounty:       nil,
				FieldCity:         "佐渡市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "相川四町目",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 相川一町目浜町: 複合町名での町目省略問題
		{
			name: "issue200-5 [新潟県佐渡市相川一町目浜町]",
			query: model.MatchQuery{
				Address:  "新潟県佐渡市相川一町目浜町",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "新潟県佐渡市相川一町目浜町",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "新潟県",
				FieldCounty:       nil,
				FieldCity:         "佐渡市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "相川一町目浜町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 相川一町目裏町
		{
			name: "issue200-6 [新潟県佐渡市相川一町目裏町]",
			query: model.MatchQuery{
				Address:  "新潟県佐渡市相川一町目裏町",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "新潟県佐渡市相川一町目裏町",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "新潟県",
				FieldCounty:       nil,
				FieldCity:         "佐渡市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "相川一町目裏町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 相川二町目浜町
		{
			name: "issue200-7 [新潟県佐渡市相川二町目浜町]",
			query: model.MatchQuery{
				Address:  "新潟県佐渡市相川二町目浜町",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "新潟県佐渡市相川二町目浜町",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "新潟県",
				FieldCounty:       nil,
				FieldCity:         "佐渡市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "相川二町目浜町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 相川二町目新浜町
		{
			name: "issue200-8 [新潟県佐渡市相川二町目新浜町]",
			query: model.MatchQuery{
				Address:  "新潟県佐渡市相川二町目新浜町",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "新潟県佐渡市相川二町目新浜町",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "新潟県",
				FieldCounty:       nil,
				FieldCity:         "佐渡市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "相川二町目新浜町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 相川三町目浜町
		{
			name: "issue200-9 [新潟県佐渡市相川三町目浜町]",
			query: model.MatchQuery{
				Address:  "新潟県佐渡市相川三町目浜町",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "新潟県佐渡市相川三町目浜町",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "新潟県",
				FieldCounty:       nil,
				FieldCity:         "佐渡市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "相川三町目浜町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 相川三町目新浜町
		{
			name: "issue200-10 [新潟県佐渡市相川三町目新浜町]",
			query: model.MatchQuery{
				Address:  "新潟県佐渡市相川三町目新浜町",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "新潟県佐渡市相川三町目新浜町",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "新潟県",
				FieldCounty:       nil,
				FieldCity:         "佐渡市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "相川三町目新浜町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 相川四町目浜町
		{
			name: "issue200-11 [新潟県佐渡市相川四町目浜町]",
			query: model.MatchQuery{
				Address:  "新潟県佐渡市相川四町目浜町",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "新潟県佐渡市相川四町目浜町",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "新潟県",
				FieldCounty:       nil,
				FieldCity:         "佐渡市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "相川四町目浜町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 相川新浜町: 町目なしパターン
		{
			name: "issue200-11a [新潟県佐渡市相川新浜町]",
			query: model.MatchQuery{
				Address:  "新潟県佐渡市相川新浜町",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "新潟県佐渡市相川新浜町",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "新潟県",
				FieldCounty:       nil,
				FieldCity:         "佐渡市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "相川新浜町",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// === いわき市平パターン ===
		// いわき市では「平X町目」はkoaza（小字）として登録されている
		// 平6町目だけkoazaが「六町目」、他は「字一町目」「字二町目」など
		// 平六町目: 町目が省略されず完全マッチすべき
		{
			name: "issue200-12 [福島県いわき市平六町目]",
			query: model.MatchQuery{
				Address:  "福島県いわき市平六町目",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "福島県いわき市平六町目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "福島県",
				FieldCounty:       nil,
				FieldCity:         "いわき市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "平",
				FieldChome:        nil,
				FieldKoaza:        "六町目",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 平一町目（koazaが「字一町目」）
		{
			name: "issue200-13 [福島県いわき市平一町目]",
			query: model.MatchQuery{
				Address:  "福島県いわき市平一町目",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "福島県いわき市平字一町目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "福島県",
				FieldCounty:       nil,
				FieldCity:         "いわき市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "平",
				FieldChome:        nil,
				FieldKoaza:        "字一町目",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 平二町目
		{
			name: "issue200-14 [福島県いわき市平二町目]",
			query: model.MatchQuery{
				Address:  "福島県いわき市平二町目",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "福島県いわき市平字二町目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "福島県",
				FieldCounty:       nil,
				FieldCity:         "いわき市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "平",
				FieldChome:        nil,
				FieldKoaza:        "字二町目",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 平三町目
		{
			name: "issue200-15 [福島県いわき市平三町目]",
			query: model.MatchQuery{
				Address:  "福島県いわき市平三町目",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "福島県いわき市平字三町目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "福島県",
				FieldCounty:       nil,
				FieldCity:         "いわき市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "平",
				FieldChome:        nil,
				FieldKoaza:        "字三町目",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 平四町目
		{
			name: "issue200-16 [福島県いわき市平四町目]",
			query: model.MatchQuery{
				Address:  "福島県いわき市平四町目",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "福島県いわき市平字四町目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "福島県",
				FieldCounty:       nil,
				FieldCity:         "いわき市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "平",
				FieldChome:        nil,
				FieldKoaza:        "字四町目",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 平五町目
		{
			name: "issue200-17 [福島県いわき市平五町目]",
			query: model.MatchQuery{
				Address:  "福島県いわき市平五町目",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "福島県いわき市平字五町目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "福島県",
				FieldCounty:       nil,
				FieldCity:         "いわき市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "平",
				FieldChome:        nil,
				FieldKoaza:        "字五町目",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 平十五町目
		{
			name: "issue200-18 [福島県いわき市平十五町目]",
			query: model.MatchQuery{
				Address:  "福島県いわき市平十五町目",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "福島県いわき市平字十五町目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "福島県",
				FieldCounty:       nil,
				FieldCity:         "いわき市",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "平",
				FieldChome:        nil,
				FieldKoaza:        "字十五町目",
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// === 京都市六町目パターン ===
		// 六町目（京都市上京区）
		{
			name: "issue200-19 [京都府京都市上京区六町目]",
			query: model.MatchQuery{
				Address:  "京都府京都市上京区六町目",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "京都府京都市上京区六町目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "京都府",
				FieldCounty:       nil,
				FieldCity:         "京都市",
				FieldWard:         "上京区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "六町目",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// === 京都市中京区・東山区 数字町目パターン ===
		// 九町目（中京区）- 地番543が存在するためparcelレベルでマッチ
		{
			name: "issue200-20 [京都府京都市中京区九町目543]",
			query: model.MatchQuery{
				Address:  "京都府京都市中京区九町目543",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "京都府京都市中京区九町目543",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "京都府",
				FieldCounty:       nil,
				FieldCity:         "京都市",
				FieldWard:         "中京区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "九町目",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      "543",
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 八町目（中京区）- 地番532が存在するためparcelレベルでマッチ
		{
			name: "issue200-21 [京都府京都市中京区八町目532]",
			query: model.MatchQuery{
				Address:  "京都府京都市中京区八町目532",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "京都府京都市中京区八町目532",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "京都府",
				FieldCounty:       nil,
				FieldCity:         "京都市",
				FieldWard:         "中京区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "八町目",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      "532",
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 七町目（中京区）- 地番100は存在しないためmachiazaレベルでマッチ
		{
			name: "issue200-22 [京都府京都市中京区七町目100]",
			query: model.MatchQuery{
				Address:  "京都府京都市中京区七町目100",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "京都府京都市中京区七町目",
			wantUnmatchedAddress: []string{"100"},
			wantStructured: map[string]any{
				FieldPref:         "京都府",
				FieldCounty:       nil,
				FieldCity:         "京都市",
				FieldWard:         "中京区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "七町目",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 三町目（東山区）- 地番23は存在しないためmachiazaレベルでマッチ
		{
			name: "issue200-23 [京都府京都市東山区三町目23]",
			query: model.MatchQuery{
				Address:  "京都府京都市東山区三町目23",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "京都府京都市東山区三町目",
			wantUnmatchedAddress: []string{"23"},
			wantStructured: map[string]any{
				FieldPref:         "京都府",
				FieldCounty:       nil,
				FieldCity:         "京都市",
				FieldWard:         "東山区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "三町目",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 二町目（東山区）- 地番50-3が存在するためparcelレベルでマッチ
		{
			name: "issue200-24 [京都府京都市東山区二町目50-3]",
			query: model.MatchQuery{
				Address:  "京都府京都市東山区二町目50-3",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "京都府京都市東山区二町目50-3",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "京都府",
				FieldCounty:       nil,
				FieldCity:         "京都市",
				FieldWard:         "東山区",
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "二町目",
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      "50",
				FieldPrcNum2:      "3",
				FieldPrcNum3:      nil,
			},
		},
	})
}
