package issues

import (
	"abrg/internal/model"
	"testing"
)

// TestIssue235 tests address normalization with directional suffix patterns (方位+側)
// Issue #235: 方位+側 が含まれる住所の正規化の不具合
// https://github.com/digital-go-jp/abr-geocoder/issues/235
//
// 問題:
// - 「東京都中央区東日本橋三丁目４番６号ICA3ビル西側」→ cityレベルに低下
// - 方位詞（西・東・北・南）と「側」の組み合わせで丁目〜番地情報がothersに移動してしまう
// - 「西」単独では residential_detail レベルで正常処理される
// - 「片側」では正常に処理される
func TestIssue235(t *testing.T) {
	runNormalizeTests(t, []normalizeTestCase{
		// === 正常動作確認用（方位+側なし） ===
		// 東日本橋 - 町名のみ（前方一致検索により市区レベルでマッチ）
		{
			name: "issue235-baseline-1 [東京都中央区東日本橋]",
			query: model.MatchQuery{
				Address:  "東京都中央区東日本橋",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelCity,
			wantMatchedAddress:   "東京都中央区",
			wantUnmatchedAddress: []string{"東日本橋"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      nil,
				FieldChome:        nil,
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 東日本橋三丁目 - 丁目まで
		{
			name: "issue235-baseline-2 [東京都中央区東日本橋三丁目]",
			query: model.MatchQuery{
				Address:  "東京都中央区東日本橋三丁目",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "東京都中央区東日本橋3丁目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "東日本橋",
				FieldChome:        "3丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 東日本橋三丁目４番 - 番まで
		{
			name: "issue235-baseline-3 [東京都中央区東日本橋三丁目４番]",
			query: model.MatchQuery{
				Address:  "東京都中央区東日本橋三丁目４番",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "東京都中央区東日本橋3丁目4",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "東日本橋",
				FieldChome:        "3丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "4",
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 東日本橋三丁目４番６号 (category=basic) - 丁目までマッチ
		{
			name: "issue235-baseline-4 [東京都中央区東日本橋三丁目４番６号] (category=basic)",
			query: model.MatchQuery{
				Address:  "東京都中央区東日本橋三丁目４番６号",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "東京都中央区東日本橋3丁目",
			wantUnmatchedAddress: []string{"4-6"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "東日本橋",
				FieldChome:        "3丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 東日本橋三丁目４番６号 (category=all) - 住居番号まで完全マッチ
		{
			name: "issue235-baseline-5 [東京都中央区東日本橋三丁目４番６号] (category=all)",
			query: model.MatchQuery{
				Address:  "東京都中央区東日本橋三丁目４番６号",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都中央区東日本橋3丁目4-6",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "東日本橋",
				FieldChome:        "3丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "4",
				FieldRsdtNum:      "6",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 東日本橋三丁目４番６号ＩＣＡ３ビル (category=basic) - 丁目まで
		{
			name: "issue235-baseline-6 [東京都中央区東日本橋三丁目４番６号ＩＣＡ３ビル] (category=basic)",
			query: model.MatchQuery{
				Address:  "東京都中央区東日本橋三丁目４番６号ＩＣＡ３ビル",
				Category: model.CategoryBasic,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "東京都中央区東日本橋3丁目",
			wantUnmatchedAddress: []string{"4-6", "ICA3ビル"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "東日本橋",
				FieldChome:        "3丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       nil,
				FieldRsdtNum:      nil,
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 東日本橋三丁目４番６号ＩＣＡ３ビル (category=all) - 住居番号までマッチ
		{
			name: "issue235-baseline-7 [東京都中央区東日本橋三丁目４番６号ＩＣＡ３ビル] (category=all)",
			query: model.MatchQuery{
				Address:  "東京都中央区東日本橋三丁目４番６号ＩＣＡ３ビル",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都中央区東日本橋3丁目4-6",
			wantUnmatchedAddress: []string{"ICA3ビル"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "東日本橋",
				FieldChome:        "3丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "4",
				FieldRsdtNum:      "6",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},

		// === 問題のあるケース（方位+側パターン） ===
		// 西側: 方位+側パターンで住居番号までマッチすべき
		{
			name: "issue235-1 [東京都中央区東日本橋三丁目４番６号ICA3ビル西側]",
			query: model.MatchQuery{
				Address:  "東京都中央区東日本橋三丁目４番６号ICA3ビル西側",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都中央区東日本橋3丁目4-6",
			wantUnmatchedAddress: []string{"ICA3ビル西側"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "東日本橋",
				FieldChome:        "3丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "4",
				FieldRsdtNum:      "6",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 東側: 方位+側パターン
		{
			name: "issue235-2 [東京都中央区東日本橋三丁目４番６号ICA3ビル東側]",
			query: model.MatchQuery{
				Address:  "東京都中央区東日本橋三丁目４番６号ICA3ビル東側",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都中央区東日本橋3丁目4-6",
			wantUnmatchedAddress: []string{"ICA3ビル東側"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "東日本橋",
				FieldChome:        "3丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "4",
				FieldRsdtNum:      "6",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 北側: 方位+側パターン
		{
			name: "issue235-3 [東京都中央区東日本橋三丁目４番６号ICA3ビル北側]",
			query: model.MatchQuery{
				Address:  "東京都中央区東日本橋三丁目４番６号ICA3ビル北側",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都中央区東日本橋3丁目4-6",
			wantUnmatchedAddress: []string{"ICA3ビル北側"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "東日本橋",
				FieldChome:        "3丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "4",
				FieldRsdtNum:      "6",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 南側: 方位+側パターン
		{
			name: "issue235-4 [東京都中央区東日本橋三丁目４番６号ICA3ビル南側]",
			query: model.MatchQuery{
				Address:  "東京都中央区東日本橋三丁目４番６号ICA3ビル南側",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都中央区東日本橋3丁目4-6",
			wantUnmatchedAddress: []string{"ICA3ビル南側"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "東日本橋",
				FieldChome:        "3丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "4",
				FieldRsdtNum:      "6",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
		// 西側2階: 方位+側+階数パターン
		{
			name: "issue235-5 [東京都中央区東日本橋三丁目４番６号ICA3ビル西側2階]",
			query: model.MatchQuery{
				Address:  "東京都中央区東日本橋三丁目４番６号ICA3ビル西側2階",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "東京都中央区東日本橋3丁目4-6",
			wantUnmatchedAddress: []string{"ICA3ビル西側2階"},
			wantStructured: map[string]any{
				FieldPref:         "東京都",
				FieldCounty:       nil,
				FieldCity:         "中央区",
				FieldWard:         nil,
				FieldMachiazaDist: nil,
				FieldKyotoSt:      nil,
				FieldOazaCho:      "東日本橋",
				FieldChome:        "3丁目",
				FieldKoaza:        nil,
				FieldBlkNum:       "4",
				FieldRsdtNum:      "6",
				FieldRsdtNum2:     nil,
				FieldPrcNum1:      nil,
				FieldPrcNum2:      nil,
				FieldPrcNum3:      nil,
			},
		},
	})
}
