package issues

import (
	"abrg/internal/model"
	"testing"
)

// TestJapaneseAddressTestdata tests addresses from Japanese-Address-testdata
// https://github.com/t-sagara/Japanese-Address-testdata/blob/main/simple.csv
func TestJapaneseAddressTestdata(t *testing.T) {
	runNormalizeTests(t, []normalizeTestCase{
		{
			// 一般的な住居表示住所
			// DB: blk_num='8' exists, rsdt_num='1' does not exist
			name: "jat001 [東京都新宿区西新宿二丁目8番1号]",
			query: model.MatchQuery{
				Address:  "東京都新宿区西新宿二丁目8番1号",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "東京都新宿区西新宿2丁目8",
			wantUnmatchedAddress: []string{"-1"},
			wantStructured: map[string]any{
				"pref":          "東京都",
				"county":        nil,
				"city":          "新宿区",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "西新宿",
				"chome":         "2丁目",
				"koaza":         nil,
				"blk_num":       "8",
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 都道府県名の省略
			// DB: blk_num='8' exists, rsdt_num='1' does not exist
			name: "jat002 [新宿区西新宿二丁目8番1号]",
			query: model.MatchQuery{
				Address:  "新宿区西新宿二丁目8番1号",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "東京都新宿区西新宿2丁目8",
			wantUnmatchedAddress: []string{"-1"},
			wantStructured: map[string]any{
				"pref":          "東京都",
				"county":        nil,
				"city":          "新宿区",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "西新宿",
				"chome":         "2丁目",
				"koaza":         nil,
				"blk_num":       "8",
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 市区町村名の省略
			// 現状マッチ不可（実装制限）
			name: "jat003 [西新宿二丁目8番1号]",
			query: model.MatchQuery{
				Address:  "西新宿二丁目8番1号",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelUnknown,
			wantMatchedAddress:   "",
			wantUnmatchedAddress: []string{"西新宿二丁目8-1"},
			wantStructured: map[string]any{
				"pref":          nil,
				"county":        nil,
				"city":          nil,
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 都道府県名と市区町村名の語幹が同じ
			// DB: prc_num1='1'は枝番付きのみ存在（1-1, 1-2, 1-3）
			name: "jat004 [山形市大字十文字１]",
			query: model.MatchQuery{
				Address:  "山形市大字十文字１",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "山形県山形市大字十文字",
			wantUnmatchedAddress: []string{"1"},
			wantStructured: map[string]any{
				"pref":          "山形県",
				"county":        nil,
				"city":          "山形市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "大字十文字",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 漢数字とアラビア数字
			// 全角数字が半角に正規化される
			name: "jat005 [東京都新宿区西新宿２丁目８番１号]",
			query: model.MatchQuery{
				Address:  "東京都新宿区西新宿２丁目８番１号",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "東京都新宿区西新宿2丁目8",
			wantUnmatchedAddress: []string{"-1"},
			wantStructured: map[string]any{
				"pref":          "東京都",
				"county":        nil,
				"city":          "新宿区",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "西新宿",
				"chome":         "2丁目",
				"koaza":         nil,
				"blk_num":       "8",
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// ハイフンによる接尾辞の省略
			name: "jat006 [東京都新宿区西新宿2-8-1]",
			query: model.MatchQuery{
				Address:  "東京都新宿区西新宿2-8-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "東京都新宿区西新宿2丁目8",
			wantUnmatchedAddress: []string{"-1"},
			wantStructured: map[string]any{
				"pref":          "東京都",
				"county":        nil,
				"city":          "新宿区",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "西新宿",
				"chome":         "2丁目",
				"koaza":         nil,
				"blk_num":       "8",
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// ノによる接尾辞の省略（漢数字+ノ+漢数字パターン）
			// 「二ノ八ノ一」→「2-8-1」に変換後、街区レベルまでマッチ
			name: "jat007 [東京都新宿区西新宿二ノ八ノ一]",
			query: model.MatchQuery{
				Address:  "東京都新宿区西新宿二ノ八ノ一",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "東京都新宿区西新宿2丁目8",
			wantUnmatchedAddress: []string{"-1"},
			wantStructured: map[string]any{
				"pref":          "東京都",
				"county":        nil,
				"city":          "新宿区",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "西新宿",
				"chome":         "2丁目",
				"koaza":         nil,
				"blk_num":       "8",
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 街区符号がアルファベット
			name: "jat008 [大阪府大阪市中央区上町A-6]",
			query: model.MatchQuery{
				Address:  "大阪府大阪市中央区上町A-6",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "大阪府大阪市中央区上町A-6",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "大阪府",
				"county":        nil,
				"city":          "大阪市",
				"ward":          "中央区",
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "上町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       "A",
				"rsdt_num":      "6",
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 市名の中に「県」
			name: "jat009 [岐阜県山県市高木1000番地1]",
			query: model.MatchQuery{
				Address:  "岐阜県山県市高木1000番地1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "岐阜県山県市高木1000-1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "岐阜県",
				"county":        nil,
				"city":          "山県市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "高木",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "1000",
				"prc_num2":      "1",
				"prc_num3":      nil,
			},
		},
		{
			// 市名の中に「郡」
			// DB: 旭町の17番データは存在しない
			name: "jat010 [愛知県蒲郡市旭町17番1号]",
			query: model.MatchQuery{
				Address:  "愛知県蒲郡市旭町17番1号",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "愛知県蒲郡市旭町",
			wantUnmatchedAddress: []string{"17-1"},
			wantStructured: map[string]any{
				"pref":          "愛知県",
				"county":        nil,
				"city":          "蒲郡市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "旭町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 市名の中に「市」（後ろの「市」までが市名）
			name: "jat011 [石川県野々市市三納1丁目1番地]",
			query: model.MatchQuery{
				Address:  "石川県野々市市三納1丁目1番地",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "石川県野々市市三納1丁目1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "石川県",
				"county":        nil,
				"city":          "野々市市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "三納",
				"chome":         "1丁目",
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "1",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 「市」から始まる大字（後ろの「市」は大字名）
			name: "jat012 [愛媛県松山市市坪西町625番地1]",
			query: model.MatchQuery{
				Address:  "愛媛県松山市市坪西町625番地1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "愛媛県松山市市坪西町625-1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "愛媛県",
				"county":        nil,
				"city":          "松山市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "市坪西町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "625",
				"prc_num2":      "1",
				"prc_num3":      nil,
			},
		},
		{
			// 2番目の「市」までが市名、3番目の「市」は大字名
			name: "jat013 [三重県四日市市市場町２１２４]",
			query: model.MatchQuery{
				Address:  "三重県四日市市市場町２１２４",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "三重県四日市市市場町2124",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "三重県",
				"county":        nil,
				"city":          "四日市市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "市場町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "2124",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 市名の中に「町」
			name: "jat014 [新潟県十日町市千歳町3丁目3番地]",
			query: model.MatchQuery{
				Address:  "新潟県十日町市千歳町3丁目3番地",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "新潟県十日町市千歳町3丁目3",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "新潟県",
				"county":        nil,
				"city":          "十日町市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "千歳町",
				"chome":         "3丁目",
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "3",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 市名の中に「都」
			name: "jat015 [宇都宮市旭1丁目1-5]",
			query: model.MatchQuery{
				Address:  "宇都宮市旭1丁目1-5",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "栃木県宇都宮市旭1丁目1-5",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "栃木県",
				"county":        nil,
				"city":          "宇都宮市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "旭",
				"chome":         "1丁目",
				"koaza":         nil,
				"blk_num":       "1",
				"rsdt_num":      "5",
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 札幌市の条省略
			// 「北３西１－７」→「北3条西1丁目7」にマッチすべき
			// DB: 北3条西1丁目 に prc_num1='7' が存在
			name: "jat016 [札幌市中央区北３西１－７]",
			query: model.MatchQuery{
				Address:  "札幌市中央区北３西１－７",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "北海道札幌市中央区北3条西1丁目7",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "北海道",
				"county":        nil,
				"city":          "札幌市",
				"ward":          "中央区",
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "北3条西",
				"chome":         "1丁目",
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "7",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat016の正しい形式（「条」を付けた場合）
			// DB: 北3条西1丁目 に prc_num1='7' が存在 → parcelレベルでマッチ
			name: "jat016-1 [札幌市中央区北3条西1丁目7]",
			query: model.MatchQuery{
				Address:  "札幌市中央区北3条西1丁目7",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "北海道札幌市中央区北3条西1丁目7",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "北海道",
				"county":        nil,
				"city":          "札幌市",
				"ward":          "中央区",
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "北3条西",
				"chome":         "1丁目",
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "7",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 数字を含む県名
			name: "jat017 [三重県津市広明町13番地]",
			query: model.MatchQuery{
				Address:  "三重県津市広明町13番地",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "三重県津市広明町13",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "三重県",
				"county":        nil,
				"city":          "津市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "広明町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "13",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 京都の通り名を含む住所
			name: "jat018 [京都市中京区寺町通御池上る上本能寺前町488番地]",
			query: model.MatchQuery{
				Address:  "京都市中京区寺町通御池上る上本能寺前町488番地",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "京都府京都市中京区寺町通御池上る上本能寺前町488",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "京都府",
				"county":        nil,
				"city":          "京都市",
				"ward":          "中京区",
				"machiaza_dist": nil,
				"kyoto_st":      "寺町通御池上る",
				"oaza_cho":      "上本能寺前町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "488",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 「大字」から始まる大字
			// DB: prc_num1='2335' は枝番付きのみ存在（2335-1, 2335-3）
			name: "jat019 [東京都西多摩郡瑞穂町大字箱根ケ崎2335番地]",
			query: model.MatchQuery{
				Address:  "東京都西多摩郡瑞穂町大字箱根ケ崎2335番地",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "東京都西多摩郡瑞穂町大字箱根ケ崎",
			wantUnmatchedAddress: []string{"2335"},
			wantStructured: map[string]any{
				"pref":          "東京都",
				"county":        "西多摩郡",
				"city":          "瑞穂町",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "大字箱根ケ崎",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名の中の「大字」が省略
			// 入力「波野小地野」→ DB「波野大字小地野」にマッチ
			name: "jat020 [熊本県阿蘇市波野小地野]",
			query: model.MatchQuery{
				Address:  "熊本県阿蘇市波野小地野",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "熊本県阿蘇市波野大字小地野",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "熊本県",
				"county":        nil,
				"city":          "阿蘇市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "波野大字小地野",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名の途中に余分な「大字」を含む住所
			// DB: 「安心院町古川」が存在し、前方一致検索でマッチ。「長坂」はDB未登録
			name: "jat021 [大分県宇佐市安心院町大字古川字長坂]",
			query: model.MatchQuery{
				Address:  "大分県宇佐市安心院町大字古川字長坂",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "大分県宇佐市安心院町古川",
			wantUnmatchedAddress: []string{"字長坂"},
			wantStructured: map[string]any{
				"pref":          "大分県",
				"county":        nil,
				"city":          "宇佐市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "安心院町古川",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名の途中に余分な「大字」を含む住所
			// 入力「哲多町大字大野」→ DB「哲多町大野」にマッチ
			name: "jat022 [岡山県新見市哲多町大字大野]",
			query: model.MatchQuery{
				Address:  "岡山県新見市哲多町大字大野",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "岡山県新見市哲多町大野",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "岡山県",
				"county":        nil,
				"city":          "新見市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "哲多町大野",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名の途中に余分な「大字」を含む住所
			// DB: 「那賀川町」+「三栗」が存在し、前方一致検索でマッチ。「堤下」はDB未登録
			name: "jat023 [徳島県阿南市那賀川町大字三栗字堤下]",
			query: model.MatchQuery{
				Address:  "徳島県阿南市那賀川町大字三栗字堤下",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "徳島県阿南市那賀川町三栗",
			wantUnmatchedAddress: []string{"字堤下"},
			wantStructured: map[string]any{
				"pref":          "徳島県",
				"county":        nil,
				"city":          "阿南市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "那賀川町",
				"chome":         nil,
				"koaza":         "三栗",
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名が漢数字で終わり丁目との区切り文字が無い
			// 入力「助七一」→「助七」にマッチし「一」が残る（元の形式を保持）
			// 期待は「助七一丁目」だが、丁目が省略されているため町字として解釈
			name: "jat024 [愛知県清須市助七一]",
			query: model.MatchQuery{
				Address:  "愛知県清須市助七一",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "愛知県清須市助七",
			wantUnmatchedAddress: []string{"一"},
			wantStructured: map[string]any{
				"pref":          "愛知県",
				"county":        nil,
				"city":          "清須市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "助七",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名が漢数字で終わり丁目との区切り文字が無い
			// 入力「与一四－１」→「与一四丁目」にマッチ
			name: "jat025 [静岡市葵区与一四－１]",
			query: model.MatchQuery{
				Address:  "静岡市葵区与一四－１",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "静岡県静岡市葵区与一四丁目",
			wantUnmatchedAddress: []string{"-1"},
			wantStructured: map[string]any{
				"pref":          "静岡県",
				"county":        nil,
				"city":          "静岡市",
				"ward":          "葵区",
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "与一",
				"chome":         "四丁目",
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 11を一一と表記
			// 入力「北一一西一三－１」→「北11条西13丁目1」にマッチ（街区番号まで解析）
			name: "jat026 [札幌市中央区北一一西一三－１]",
			query: model.MatchQuery{
				Address:  "札幌市中央区北一一西一三－１",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "北海道札幌市中央区北11条西13丁目1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "北海道",
				"county":        nil,
				"city":          "札幌市",
				"ward":          "中央区",
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "北11条西",
				"chome":         "13丁目",
				"koaza":         nil,
				"blk_num":       "1",
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名が漢数字で終わり地番との区切り文字が無い
			// 入力「古豊千六」→「古豊千」にマッチし「六」が残る（元の形式を保持）
			name: "jat027 [鳥取県米子市古豊千六]",
			query: model.MatchQuery{
				Address:  "鳥取県米子市古豊千六",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "鳥取県米子市古豊千",
			wantUnmatchedAddress: []string{"六"},
			wantStructured: map[string]any{
				"pref":          "鳥取県",
				"county":        nil,
				"city":          "米子市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "古豊千",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名が漢数字で終わり地番との区切り文字が無い
			// 入力「福万619」→「福万」にマッチし「619」が残る（地番データなし）
			name: "jat028 [鳥取県米子市福万619]",
			query: model.MatchQuery{
				Address:  "鳥取県米子市福万619",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "鳥取県米子市福万",
			wantUnmatchedAddress: []string{"619"},
			wantStructured: map[string]any{
				"pref":          "鳥取県",
				"county":        nil,
				"city":          "米子市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "福万",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 字名に「ノ」が含まれる
			// 入力「富岡町トノ町６５－６」→「富岡町」+「トノ町」+「65-6」にマッチ
			name: "jat029 [徳島県阿南市富岡町トノ町６５－６]",
			query: model.MatchQuery{
				Address:  "徳島県阿南市富岡町トノ町６５－６",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "徳島県阿南市富岡町トノ町65-6",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "徳島県",
				"county":        nil,
				"city":          "阿南市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "富岡町",
				"chome":         nil,
				"koaza":         "トノ町",
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "65",
				"prc_num2":      "6",
				"prc_num3":      nil,
			},
		},
		{
			// 大字名に余分な「ノ」が含まれる
			// 入力「鷹ノ巣」→ DB「大字鷹巣」だが、「ノ」の差異で大字レベルは未マッチ
			// 前方一致検索により市町村までマッチ
			// TODO: 「ノ」除去の正規化が必要（大字レベルマッチのため）
			name: "jat030 [埼玉県大里郡寄居町鷹ノ巣５２−１]",
			query: model.MatchQuery{
				Address:  "埼玉県大里郡寄居町鷹ノ巣５２−１",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelCity,
			wantMatchedAddress:   "埼玉県大里郡寄居町",
			wantUnmatchedAddress: []string{"鷹ノ巣52-1"},
			wantStructured: map[string]any{
				"pref":          "埼玉県",
				"county":        "大里郡",
				"city":          "寄居町",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat030の補足：「ノ」なしの場合は正しくparcelまでマッチ
			// 入力「鷹巣」→ DB「大字鷹巣」に完全マッチ
			name: "jat030-1 [埼玉県大里郡寄居町鷹巣52-1] ノなし",
			query: model.MatchQuery{
				Address:  "埼玉県大里郡寄居町鷹巣52-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "埼玉県大里郡寄居町大字鷹巣52-1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "埼玉県",
				"county":        "大里郡",
				"city":          "寄居町",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "大字鷹巣",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "52",
				"prc_num2":      "1",
				"prc_num3":      nil,
			},
		},
		{
			// 地番に「甲」が含まれる
			// 入力「国定町２の甲１９９４」→「国定町二丁目」にマッチし「の甲1994」が残る
			// DB: 地番「甲1994」は存在しない
			name: "jat031 [群馬県伊勢崎市国定町２の甲１９９４]",
			query: model.MatchQuery{
				Address:  "群馬県伊勢崎市国定町２の甲１９９４",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "群馬県伊勢崎市国定町二丁目",
			wantUnmatchedAddress: []string{"の甲1994"},
			wantStructured: map[string]any{
				"pref":          "群馬県",
				"county":        nil,
				"city":          "伊勢崎市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "国定町",
				"chome":         "二丁目",
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 字名に「ノ」が含まれる
			// 入力「久保田字一ノ山１５２３」→「久保田」にマッチし「一ノ山1523」が残る
			// DB: 字「一ノ山」はkoazaとして未登録のためmachiaza止まり
			name: "jat032 [千葉県袖ケ浦市久保田字一ノ山１５２３]",
			query: model.MatchQuery{
				Address:  "千葉県袖ケ浦市久保田字一ノ山１５２３",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "千葉県袖ケ浦市久保田",
			wantUnmatchedAddress: []string{"一ノ山1523"},
			wantStructured: map[string]any{
				"pref":          "千葉県",
				"county":        nil,
				"city":          "袖ケ浦市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "久保田",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 字名が「ノ」で終わっている
			// 入力「山崎町上ノ１５０２」→「山崎町上ノ」にマッチ
			name: "jat033 [兵庫県宍粟市山崎町上ノ１５０２]",
			query: model.MatchQuery{
				Address:  "兵庫県宍粟市山崎町上ノ１５０２",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "兵庫県宍粟市山崎町上ノ",
			wantUnmatchedAddress: []string{"1502"},
			wantStructured: map[string]any{
				"pref":          "兵庫県",
				"county":        nil,
				"city":          "宍粟市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "山崎町上ノ",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 字名が「ノ」
			// 入力「軽海町ノ１４－１」→「軽海町ノ14-1」にマッチ（parcelレベル）
			name: "jat034 [石川県小松市軽海町ノ１４－１]",
			query: model.MatchQuery{
				Address:  "石川県小松市軽海町ノ１４－１",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "石川県小松市軽海町ノ14-1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "石川県",
				"county":        nil,
				"city":          "小松市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "軽海町",
				"chome":         nil,
				"koaza":         "ノ",
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "14",
				"prc_num2":      "1",
				"prc_num3":      nil,
			},
		},
		{
			// 字名「ノ」のあとにハイフンで地番が続く
			// 入力「軽海町ノ－１４－１」→ 小字「ノ」+ 地番14-1 にマッチ（issue #259 の
			// 小字フォールバックにより字名として解決できるようになった）
			name: "jat035 [石川県小松市軽海町ノ－１４－１]",
			query: model.MatchQuery{
				Address:  "石川県小松市軽海町ノ－１４－１",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "石川県小松市軽海町ノ14-1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "石川県",
				"county":        nil,
				"city":          "小松市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "軽海町",
				"chome":         nil,
				"koaza":         "ノ",
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "14",
				"prc_num2":      "1",
				"prc_num3":      nil,
			},
		},
		{
			// 字名が「字」
			// 入力「林町字１４８」→「林町」にマッチ
			name: "jat036 [香川県高松市林町字１４８]",
			query: model.MatchQuery{
				Address:  "香川県高松市林町字１４８",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "香川県高松市林町",
			wantUnmatchedAddress: []string{"148"},
			wantStructured: map[string]any{
				"pref":          "香川県",
				"county":        nil,
				"city":          "高松市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "林町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat036の補足：枝番をつけるとparcelまでマッチ
			// 地番148は存在しないが148-1は存在する
			name: "jat036-1 [香川県高松市林町字148-1]",
			query: model.MatchQuery{
				Address:  "香川県高松市林町字148-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "香川県高松市林町148-1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "香川県",
				"county":        nil,
				"city":          "高松市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "林町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "148",
				"prc_num2":      "1",
				"prc_num3":      nil,
			},
		},
		{
			// 字名が「ケ」
			// 入力「一ノ宮町ケ５０」→「一ノ宮町ケ」にマッチ（machiaza_detailレベル）
			name: "jat037 [石川県羽咋市一ノ宮町ケ５０]",
			query: model.MatchQuery{
				Address:  "石川県羽咋市一ノ宮町ケ５０",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県羽咋市一ノ宮町ケ",
			wantUnmatchedAddress: []string{"50"},
			wantStructured: map[string]any{
				"pref":          "石川県",
				"county":        nil,
				"city":          "羽咋市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "一ノ宮町",
				"chome":         nil,
				"koaza":         "ケ",
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名の「町」が省略
			// 入力「茨城県龍ケ崎市薄倉」→ DB「茨城県龍ケ崎市薄倉薄倉町」にマッチ
			// 都道府県省略時は「町」が省略されているとマッチできずunknown
			// TODO: 都道府県省略時の市名認識改善
			name: "jat038 [龍ケ崎市薄倉２３６４]",
			query: model.MatchQuery{
				Address:  "龍ケ崎市薄倉２３６４",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelUnknown,
			wantMatchedAddress:   "",
			wantUnmatchedAddress: []string{"龍ケ崎市薄倉2364"},
			wantStructured: map[string]any{
				"pref":          nil,
				"county":        nil,
				"city":          nil,
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat038の補足：茨城県をつけた場合はmachiazaまでマッチ
			// 入力「薄倉」→ DB「薄倉町」にファジーマッチ
			// 地番2364単独はDBに存在しない（2364-1, 2364-2等の枝番のみ存在）ためmachiazaでマッチ
			name: "jat038-1 [茨城県龍ケ崎市薄倉2364]",
			query: model.MatchQuery{
				Address:  "茨城県龍ケ崎市薄倉2364",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "茨城県龍ケ崎市薄倉町",
			wantUnmatchedAddress: []string{"2364"},
			wantStructured: map[string]any{
				"pref":          "茨城県",
				"county":        nil,
				"city":          "龍ケ崎市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "薄倉町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名の途中の「町」が省略
			// 入力「秋保湯元」→ DB「秋保町湯元」にマッチできず、市区レベル止まり
			name: "jat039 [宮城県仙台市太白区秋保湯元字寺田原40-7]",
			query: model.MatchQuery{
				Address:  "宮城県仙台市太白区秋保湯元字寺田原40-7",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelCity,
			wantMatchedAddress:   "宮城県仙台市太白区",
			wantUnmatchedAddress: []string{"秋保湯元字寺田原40-7"},
			wantStructured: map[string]any{
				"pref":     "宮城県",
				"county":   nil,
				"city":     "仙台市",
				"ward":     "太白区",
				"oaza_cho": nil,
				"chome":    nil,
				"koaza":    nil,
			},
		},
		{
			// 「町」あり → DB「秋保町湯元」に正確マッチ、地番まで解決
			name: "jat039-1 [宮城県仙台市太白区秋保町湯元字寺田原40-7]",
			query: model.MatchQuery{
				Address:  "宮城県仙台市太白区秋保町湯元字寺田原40-7",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "宮城県仙台市太白区秋保町湯元字寺田原40-7",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":     "宮城県",
				"county":   nil,
				"city":     "仙台市",
				"ward":     "太白区",
				"oaza_cho": "秋保町湯元",
				"chome":    nil,
				"koaza":    "字寺田原",
				"prc_num1": "40",
				"prc_num2": "7",
				"prc_num3": nil,
			},
		},
		{
			// 大字名の途中に余分な「町」
			// 入力「菱刈町前目」→ DB「菱刈前目」にfuzzy matchで正しくマッチ
			name: "jat040 [鹿児島県伊佐市菱刈町前目２０１３番地]",
			query: model.MatchQuery{
				Address:  "鹿児島県伊佐市菱刈町前目２０１３番地",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "鹿児島県伊佐市菱刈前目",
			wantUnmatchedAddress: []string{"2013"},
			wantStructured: map[string]any{
				"pref":          "鹿児島県",
				"county":        nil,
				"city":          "伊佐市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "菱刈前目",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat040の補足：「町」なし＋枝番でparcelまでマッチ
			// DB上は「菱刈前目」のため「町」を除き、地番2013-1を指定
			name: "jat040-1 [鹿児島県伊佐市菱刈前目2013-1]",
			query: model.MatchQuery{
				Address:  "鹿児島県伊佐市菱刈前目2013-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "鹿児島県伊佐市菱刈前目2013-1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "鹿児島県",
				"county":        nil,
				"city":          "伊佐市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "菱刈前目",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "2013",
				"prc_num2":      "1",
				"prc_num3":      nil,
			},
		},
		{
			// 大字名に「町」を追加すると別の大字になる
			// 入力「水橋開発212」→「水橋開発」にマッチ（「水橋開発町」とは別）
			name: "jat041 [富山県富山市水橋開発212]",
			query: model.MatchQuery{
				Address:  "富山県富山市水橋開発212",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "富山県富山市水橋開発212",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "富山県",
				"county":        nil,
				"city":          "富山市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "水橋開発",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "212",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat041の補足：「町」を追加すると別の大字「水橋開発町」にマッチ
			// 「水橋開発」と「水橋開発町」は両方存在する別の大字、地番212は水橋開発町に存在しない
			name: "jat041-1 [富山県富山市水橋開発町212]",
			query: model.MatchQuery{
				Address:  "富山県富山市水橋開発町212",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "富山県富山市水橋開発町",
			wantUnmatchedAddress: []string{"212"},
			wantStructured: map[string]any{
				"pref":          "富山県",
				"county":        nil,
				"city":          "富山市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "水橋開発町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名の「町」を省略すると別の大字になる
			// 入力「水橋開発町９６」→「水橋開発町」にマッチ（地番データなし）
			name: "jat042 [富山県富山市水橋開発町９６]",
			query: model.MatchQuery{
				Address:  "富山県富山市水橋開発町９６",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "富山県富山市水橋開発町",
			wantUnmatchedAddress: []string{"96"},
			wantStructured: map[string]any{
				"pref":          "富山県",
				"county":        nil,
				"city":          "富山市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "水橋開発町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat042の補足：「町」を省略すると別の大字「水橋開発」にマッチ
			// 「水橋開発」と「水橋開発町」は両方存在する別の大字
			name: "jat042-1 [富山県富山市水橋開発96]",
			query: model.MatchQuery{
				Address:  "富山県富山市水橋開発96",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "富山県富山市水橋開発96",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "富山県",
				"county":        nil,
				"city":          "富山市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "水橋開発",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "96",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名の「通」を「通り」と表記
			// 都道府県省略時は滝上町が認識できず prefレベル
			name: "jat043 [滝上町字滝上市街地３条通り2-9]",
			query: model.MatchQuery{
				Address:  "滝上町字滝上市街地３条通り2-9",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelPrefecture,
			wantMatchedAddress:   "北海道",
			wantUnmatchedAddress: []string{"滝上町字滝上市街地3条通り2-9"},
			wantStructured: map[string]any{
				"pref":          "北海道",
				"county":        nil,
				"city":          nil,
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat043の補足：都道府県+「ノ」+「通」（「り」なし）
			// 地番9は存在しないが9-1は存在するため枝番をつけると地番までマッチする
			name: "jat043-1 [北海道紋別郡滝上町字滝ノ上市街地3条通2-9-1]",
			query: model.MatchQuery{
				Address:  "北海道紋別郡滝上町字滝ノ上市街地3条通2-9-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "北海道紋別郡滝上町字滝ノ上市街地3条通2丁目9-1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "北海道",
				"county":        "紋別郡",
				"city":          "滝上町",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "字滝ノ上市街地3条通",
				"chome":         "2丁目",
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "9",
				"prc_num2":      "1",
				"prc_num3":      nil,
			},
		},
		{
			// 大字名に「条」を含む
			// 入力「上条町１」→「上条町1丁目」にマッチ
			name: "jat044 [愛知県春日井市上条町１]",
			query: model.MatchQuery{
				Address:  "愛知県春日井市上条町１",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "愛知県春日井市上条町1丁目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "愛知県",
				"county":        nil,
				"city":          "春日井市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "上条町",
				"chome":         "1丁目",
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名の「ノ」が省略
			// 入力「上町１」→ DB「上ノ町」だが、「ノ」の差異で未マッチ
			name: "jat045 [愛知県春日井市上町１]",
			query: model.MatchQuery{
				Address:  "愛知県春日井市上町１",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelCity,
			wantMatchedAddress:   "愛知県春日井市",
			wantUnmatchedAddress: []string{"上町1"},
			wantStructured: map[string]any{
				"pref":          "愛知県",
				"county":        nil,
				"city":          "春日井市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat045の補足：「ノ」をつけるとmachiaza_detailまでマッチ
			// DB上は「上ノ町」のため「ノ」を補うとマッチする
			name: "jat045-1 [愛知県春日井市上ノ町1]",
			query: model.MatchQuery{
				Address:  "愛知県春日井市上ノ町1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "愛知県春日井市上ノ町1丁目",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "愛知県",
				"county":        nil,
				"city":          "春日井市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "上ノ町",
				"chome":         "1丁目",
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 字名の「番」がハイフンで省略
			// 入力「久保野２ー５」→ 「字久保野二番」にマッチ（「２」が「二番」に対応）
			name: "jat046 [宮城県仙台市宮城野区福室字久保野２ー５]",
			query: model.MatchQuery{
				Address:  "宮城県仙台市宮城野区福室字久保野２ー５",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "宮城県仙台市宮城野区福室字久保野二番",
			wantUnmatchedAddress: []string{"2-5"},
			wantStructured: map[string]any{
				"pref":          "宮城県",
				"county":        nil,
				"city":          "仙台市",
				"ward":          "宮城野区",
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "福室",
				"chome":         nil,
				"koaza":         "字久保野二番",
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat046の補足：「二番」を漢数字で書くとparcelまでマッチ
			// DB上は「字久保野二番」のため漢数字で指定するとマッチする
			name: "jat046-1 [宮城県仙台市宮城野区福室字久保野二番5]",
			query: model.MatchQuery{
				Address:  "宮城県仙台市宮城野区福室字久保野二番5",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "宮城県仙台市宮城野区福室字久保野二番5",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "宮城県",
				"county":        nil,
				"city":          "仙台市",
				"ward":          "宮城野区",
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "福室",
				"chome":         nil,
				"koaza":         "字久保野二番",
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "5",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名の「番丁」がハイフンで省略
			// 入力「宇多津町浜２の１２」→「浜」にマッチ（番丁データなし）
			name: "jat047 [香川県綾歌郡宇多津町浜２の１２]",
			query: model.MatchQuery{
				Address:  "香川県綾歌郡宇多津町浜２の１２",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "香川県綾歌郡宇多津町浜",
			wantUnmatchedAddress: []string{"2-12"},
			wantStructured: map[string]any{
				"pref":          "香川県",
				"county":        "綾歌郡",
				"city":          "宇多津町",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "浜",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat047の補足：「番丁」を明記するとmachiazaまでマッチ
			// DB上は「浜二番丁」のため「番丁」を補うとマッチする（地番データなし）
			name: "jat047-1 [香川県綾歌郡宇多津町浜二番丁12]",
			query: model.MatchQuery{
				Address:  "香川県綾歌郡宇多津町浜二番丁12",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "香川県綾歌郡宇多津町浜二番丁",
			wantUnmatchedAddress: []string{"12"},
			wantStructured: map[string]any{
				"pref":          "香川県",
				"county":        "綾歌郡",
				"city":          "宇多津町",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "浜二番丁",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名の「番町」がハイフンで省略
			// 入力「東１６－４８」→ DB「東十六番町」だが未マッチ
			name: "jat048 [青森県十和田市東１６－４８]",
			query: model.MatchQuery{
				Address:  "青森県十和田市東１６－４８",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelCity,
			wantMatchedAddress:   "青森県十和田市",
			wantUnmatchedAddress: []string{"東16-48"},
			wantStructured: map[string]any{
				"pref":          "青森県",
				"county":        nil,
				"city":          "十和田市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat048の補足：「番町」を明記するとrsdtdsp_blkまでマッチ
			// DB上は「東十六番町」のため漢数字で指定するとマッチする
			name: "jat048-1 [青森県十和田市東十六番町48]",
			query: model.MatchQuery{
				Address:  "青森県十和田市東十六番町48",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "青森県十和田市東十六番町48",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "青森県",
				"county":        nil,
				"city":          "十和田市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "東十六番町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       "48",
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 字名の「号」が省略
			// 入力「鹿島町１」→「鹿島町」にマッチ（「一号」データなし）
			name: "jat049 [石川県白山市鹿島町１]",
			query: model.MatchQuery{
				Address:  "石川県白山市鹿島町１",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "石川県白山市鹿島町",
			wantUnmatchedAddress: []string{"1"},
			wantStructured: map[string]any{
				"pref":          "石川県",
				"county":        nil,
				"city":          "白山市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "鹿島町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 字名の「号」が省略
			// 入力「園部町河原町４」→「園部町河原町4号」にマッチし、unmatchedはnull
			name: "jat050 [京都府南丹市園部町河原町４]",
			query: model.MatchQuery{
				Address:  "京都府南丹市園部町河原町４",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "京都府南丹市園部町河原町4号",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "京都府",
				"county":        nil,
				"city":          "南丹市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "園部町河原町",
				"chome":         nil,
				"koaza":         "4号",
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 字名の「区」が省略
			// 入力「留辺蘂町温根湯温泉１」→「留辺蘂町温根湯温泉」にマッチ（「一区」データなし）
			name: "jat051 [北海道北見市留辺蘂町温根湯温泉１]",
			query: model.MatchQuery{
				Address:  "北海道北見市留辺蘂町温根湯温泉１",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "北海道北見市留辺蘂町温根湯温泉",
			wantUnmatchedAddress: []string{"1"},
			wantStructured: map[string]any{
				"pref":          "北海道",
				"county":        nil,
				"city":          "北見市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "留辺蘂町温根湯温泉",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 字名と地番の間に余分な「の」
			// 都道府県省略時は涌谷町が認識できず prefレベル
			name: "jat052 [涌谷町涌谷八方谷１の16]",
			query: model.MatchQuery{
				Address:  "涌谷町涌谷八方谷１の16",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelPrefecture,
			wantMatchedAddress:   "宮城県",
			wantUnmatchedAddress: []string{"涌谷町涌谷八方谷1-16"},
			wantStructured: map[string]any{
				"pref":          "宮城県",
				"county":        nil,
				"city":          nil,
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat052の補足：「字八方谷一」を明記するとparcelまでマッチ
			// DB上は「字八方谷一」のため漢数字で指定するとマッチする
			name: "jat052-1 [宮城県遠田郡涌谷町涌谷字八方谷一1]",
			query: model.MatchQuery{
				Address:  "宮城県遠田郡涌谷町涌谷字八方谷一1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "宮城県遠田郡涌谷町涌谷字八方谷一1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "宮城県",
				"county":        "遠田郡",
				"city":          "涌谷町",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "涌谷",
				"chome":         nil,
				"koaza":         "字八方谷一",
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "1",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat052の補足：郡をつけるとmachiaza_detailまでマッチ
			// 郡なしだとprefまでだが、郡をつけると「字八方谷一」までマッチする
			name: "jat052-2 [宮城県遠田郡涌谷町涌谷八方谷１の16]",
			query: model.MatchQuery{
				Address:  "宮城県遠田郡涌谷町涌谷八方谷１の16",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "宮城県遠田郡涌谷町涌谷字八方谷一",
			wantUnmatchedAddress: []string{"1-16"},
			wantStructured: map[string]any{
				"pref":          "宮城県",
				"county":        "遠田郡",
				"city":          "涌谷町",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "涌谷",
				"chome":         nil,
				"koaza":         "字八方谷一",
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 地域自治区「胆沢区」（H30.3.31まで）
			// 入力「胆沢区小山」→ DB「胆沢小山」だが、「区」の差異で未マッチ
			name: "jat053 [岩手県奥州市胆沢区小山字道場40-1]",
			query: model.MatchQuery{
				Address:  "岩手県奥州市胆沢区小山字道場40-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelCity,
			wantMatchedAddress:   "岩手県奥州市",
			wantUnmatchedAddress: []string{"胆沢区小山字道場40-1"},
			wantStructured: map[string]any{
				"pref":          "岩手県",
				"county":        nil,
				"city":          "奥州市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat053の補足：「区」を除くとparcelまでマッチ
			// DB上は「胆沢小山」のため「区」を除くとマッチする
			name: "jat053-1 [岩手県奥州市胆沢小山字道場40-1]",
			query: model.MatchQuery{
				Address:  "岩手県奥州市胆沢小山字道場40-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "岩手県奥州市胆沢小山字道場40-1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "岩手県",
				"county":        nil,
				"city":          "奥州市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "胆沢小山",
				"chome":         nil,
				"koaza":         "字道場",
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "40",
				"prc_num2":      "1",
				"prc_num3":      nil,
			},
		},
		{
			// 大字名に余分な「区」
			name: "jat054 [青森県八戸市南郷区大字島守字赤羽６]",
			query: model.MatchQuery{
				Address:  "青森県八戸市南郷区大字島守字赤羽６",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelCity,
			wantMatchedAddress:   "青森県八戸市",
			wantUnmatchedAddress: []string{"南郷区大字島守字赤羽6"},
			wantStructured: map[string]any{
				"pref":          "青森県",
				"county":        nil,
				"city":          "八戸市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 省略可能な字
			name: "jat055 [静岡県駿東郡小山町竹之下字上ノ原５５４]",
			query: model.MatchQuery{
				Address:  "静岡県駿東郡小山町竹之下字上ノ原５５４",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelCity,
			wantMatchedAddress:   "静岡県駿東郡小山町",
			wantUnmatchedAddress: []string{"竹之下字上ノ原554"},
			wantStructured: map[string]any{
				"pref":          "静岡県",
				"county":        "駿東郡",
				"city":          "小山町",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 字なしで大字＋番地のみ
			name: "jat055b [静岡県駿東郡小山町竹之下５５４]",
			query: model.MatchQuery{
				Address:  "静岡県駿東郡小山町竹之下５５４",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "静岡県駿東郡小山町竹之下",
			wantUnmatchedAddress: []string{"554"},
			wantStructured: map[string]any{
				"pref":          "静岡県",
				"county":        "駿東郡",
				"city":          "小山町",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "竹之下",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名の途中に省略可能な字名
			// 入力「八街字七本松ろ」→ DB「八街ろ」だが未マッチ
			name: "jat056 [千葉県八街市八街字七本松ろ９７－１]",
			query: model.MatchQuery{
				Address:  "千葉県八街市八街字七本松ろ９７－１",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelCity,
			wantMatchedAddress:   "千葉県八街市",
			wantUnmatchedAddress: []string{"八街字七本松ろ97-1"},
			wantStructured: map[string]any{
				"pref":          "千葉県",
				"county":        nil,
				"city":          "八街市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat056の補足：「字七本松」を除くとmachiazaまでマッチ
			// DB上は「八街ろ」のため「字七本松」を除くとマッチする（地番データなし）
			name: "jat056-1 [千葉県八街市八街ろ97-1]",
			query: model.MatchQuery{
				Address:  "千葉県八街市八街ろ97-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "千葉県八街市八街ろ",
			wantUnmatchedAddress: []string{"97-1"},
			wantStructured: map[string]any{
				"pref":          "千葉県",
				"county":        nil,
				"city":          "八街市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "八街ろ",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 省略可能な字
			// 入力「礒部字下河原」→ DB「大字磯部」だが「礒」と「磯」は別の漢字で未マッチ
			// 「礒」(U+7912)と「磯」(U+78EF)は異体字ではなく別の漢字
			name: "jat057 [長野県千曲市礒部字下河原１１３７]",
			query: model.MatchQuery{
				Address:  "長野県千曲市礒部字下河原１１３７",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelCity,
			wantMatchedAddress:   "長野県千曲市",
			wantUnmatchedAddress: []string{"礒部字下河原1137"},
			wantStructured: map[string]any{
				"pref":          "長野県",
				"county":        nil,
				"city":          "千曲市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat057の補足：「磯」（正しい漢字）を使用するとparcelまでマッチ
			// DB上は「大字磯部」で地番1137-1が存在
			name: "jat057-1 [長野県千曲市磯部1137-1]",
			query: model.MatchQuery{
				Address:  "長野県千曲市磯部1137-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "長野県千曲市大字磯部1137-1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "長野県",
				"county":        nil,
				"city":          "千曲市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "大字磯部",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "1137",
				"prc_num2":      "1",
				"prc_num3":      nil,
			},
		},
		{
			// jat057の補足：「磯」（正しい漢字）+「字下河原」を付けるとmachiazaまで
			// DB上に「字下河原」がないため、「下河原1137」がunmatchedになる
			name: "jat057-2 [長野県千曲市磯部字下河原1137]",
			query: model.MatchQuery{
				Address:  "長野県千曲市磯部字下河原1137",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "長野県千曲市大字磯部",
			wantUnmatchedAddress: []string{"下河原1137"},
			wantStructured: map[string]any{
				"pref":          "長野県",
				"county":        nil,
				"city":          "千曲市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "大字磯部",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 地番に「ハ」「丙」を含む
			// 入力「嬉野町大字下野字長波須ハ丙１２２４」→「嬉野町大字下野」にマッチ
			// 「字長波須ハ丙」はDB上に存在しないため、「長波須ハ丙1224」がunmatchedになる
			name: "jat058 [佐賀県嬉野市嬉野町大字下野字長波須ハ丙１２２４]",
			query: model.MatchQuery{
				Address:  "佐賀県嬉野市嬉野町大字下野字長波須ハ丙１２２４",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "佐賀県嬉野市嬉野町大字下野",
			wantUnmatchedAddress: []string{"長波須ハ丙1224"},
			wantStructured: map[string]any{
				"pref":          "佐賀県",
				"county":        nil,
				"city":          "嬉野市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "嬉野町大字下野",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat058の補足：「字長波須ハ」を省略し「下野丙」と正しく書くとmachiazaまでマッチ
			// DB上は「嬉野町大字下野丙」が独立した大字として存在（地番データなし）
			name: "jat058-1 [佐賀県嬉野市嬉野町大字下野丙1224]",
			query: model.MatchQuery{
				Address:  "佐賀県嬉野市嬉野町大字下野丙1224",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "佐賀県嬉野市嬉野町大字下野丙",
			wantUnmatchedAddress: []string{"1224"},
			wantStructured: map[string]any{
				"pref":          "佐賀県",
				"county":        nil,
				"city":          "嬉野市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "嬉野町大字下野丙",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字が無い住所
			// 入力「桧原村467-1」→ DB「檜原村」にマッチ（桧→檜）
			name: "jat059 [東京都西多摩郡桧原村467-1]",
			query: model.MatchQuery{
				Address:  "東京都西多摩郡桧原村467-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "東京都西多摩郡檜原村",
			wantUnmatchedAddress: []string{"467-1"},
			wantStructured: map[string]any{
				"pref":          "東京都",
				"county":        "西多摩郡",
				"city":          "檜原村",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字が無い
			// 入力「佐川町字若枝甲４８５」→「佐川町」にマッチ（字若枝データなし）
			name: "jat060 [高知県高岡郡佐川町字若枝甲４８５]",
			query: model.MatchQuery{
				Address:  "高知県高岡郡佐川町字若枝甲４８５",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelCity,
			wantMatchedAddress:   "高知県高岡郡佐川町",
			wantUnmatchedAddress: []string{"字若枝甲485"},
			wantStructured: map[string]any{
				"pref":          "高知県",
				"county":        "高岡郡",
				"city":          "佐川町",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 省略できない字
			// 都道府県省略だが「美馬市」から徳島県を補完
			// 「西上野」は省略できない字としてkoazaに含まれる
			name: "jat061 [美馬市脇町猪尻西上野61-1]",
			query: model.MatchQuery{
				Address:  "美馬市脇町猪尻西上野61-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "徳島県美馬市脇町大字猪尻字西上野61-1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "徳島県",
				"county":        nil,
				"city":          "美馬市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "脇町大字猪尻",
				"chome":         nil,
				"koaza":         "字西上野",
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "61",
				"prc_num2":      "1",
				"prc_num3":      nil,
			},
		},
		{
			// 脱落地
			// 「97乙」→地番97乙は脱落地として未マッチ
			name: "jat062 [福島県いわき市平上高久塚田97乙]",
			query: model.MatchQuery{
				Address:  "福島県いわき市平上高久塚田97乙",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "福島県いわき市平上高久字塚田",
			wantUnmatchedAddress: []string{"97", "乙"},
			wantStructured: map[string]any{
				"pref":          "福島県",
				"county":        nil,
				"city":          "いわき市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "平上高久",
				"chome":         nil,
				"koaza":         "字塚田",
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 異体字
			// 都道府県省略時、「竜ヶ崎市」を「龍ケ崎市」として認識できずunknown
			name: "jat063 [竜ヶ崎市字米町3903]",
			query: model.MatchQuery{
				Address:  "竜ヶ崎市字米町3903",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelUnknown,
			wantMatchedAddress:   "",
			wantUnmatchedAddress: []string{"竜ヶ崎市字米町3903"},
			wantStructured: map[string]any{
				"pref":          nil,
				"county":        nil,
				"city":          nil,
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 複数の候補が存在する（千葉県千葉市中央区）
			// 都道府県・市区町村省略時は最初にマッチした候補（東京都中央区、特別区）
			name: "jat064 [中央区中央１－１]",
			query: model.MatchQuery{
				Address:  "中央区中央１－１",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelCity,
			wantMatchedAddress:   "東京都中央区",
			wantUnmatchedAddress: []string{"中央1-1"},
			wantStructured: map[string]any{
				"pref":          "東京都",
				"county":        nil,
				"city":          "中央区",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat064の補足：「千葉市」を付けるとrsdtdsp_blkまでマッチ
			// pref指定だけでは「中央区」から千葉市中央区を特定できない
			name: "jat064-1 [千葉市中央区中央1-1]",
			query: model.MatchQuery{
				Address:  "千葉市中央区中央1-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "千葉県千葉市中央区中央1丁目1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "千葉県",
				"county":        nil,
				"city":          "千葉市",
				"ward":          "中央区",
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "中央",
				"chome":         "1丁目",
				"koaza":         nil,
				"blk_num":       "1",
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 複数の候補が存在する（神奈川県相模原市中央区）
			// 注意：jat064と同じ入力だが期待する結果は神奈川県。現実装では東京都中央区にマッチ
			name: "jat065 [中央区中央１－１]",
			query: model.MatchQuery{
				Address:  "中央区中央１－１",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelCity,
			wantMatchedAddress:   "東京都中央区",
			wantUnmatchedAddress: []string{"中央1-1"},
			wantStructured: map[string]any{
				"pref":          "東京都",
				"county":        nil,
				"city":          "中央区",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat065の補足：「相模原市」を付けるとrsdtdsp_blkまでマッチ
			name: "jat065-1 [相模原市中央区中央1-1]",
			query: model.MatchQuery{
				Address:  "相模原市中央区中央1-1",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "神奈川県相模原市中央区中央1丁目1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "神奈川県",
				"county":        nil,
				"city":          "相模原市",
				"ward":          "中央区",
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "中央",
				"chome":         "1丁目",
				"koaza":         nil,
				"blk_num":       "1",
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 島名を含む
			// 「八丈島」は島名として未対応、都道府県のみマッチ
			name: "jat066 [東京都八丈島八丈町大賀郷2551番地2]",
			query: model.MatchQuery{
				Address:  "東京都八丈島八丈町大賀郷2551番地2",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelPrefecture,
			wantMatchedAddress:   "東京都",
			wantUnmatchedAddress: []string{"八丈島八丈町大賀郷2551-2"},
			wantStructured: map[string]any{
				"pref":          "東京都",
				"county":        nil,
				"city":          nil,
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat066の補足：「八丈島」を除くとparcelまでマッチ（大賀郷は地番データあり）
			name: "jat066-1 [東京都八丈町大賀郷2551-2]",
			query: model.MatchQuery{
				Address:  "東京都八丈町大賀郷2551-2",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "東京都八丈町大賀郷2551-2",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "東京都",
				"county":        nil,
				"city":          "八丈町",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "大賀郷",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "2551",
				"prc_num2":      "2",
				"prc_num3":      nil,
			},
		},
		{
			// 島名を含む
			// 「三宅島」は島名として未対応、都道府県のみマッチ
			name: "jat067 [東京都三宅島三宅村阿古497番地]",
			query: model.MatchQuery{
				Address:  "東京都三宅島三宅村阿古497番地",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelPrefecture,
			wantMatchedAddress:   "東京都",
			wantUnmatchedAddress: []string{"三宅島三宅村阿古497"},
			wantStructured: map[string]any{
				"pref":          "東京都",
				"county":        nil,
				"city":          nil,
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat067の補足：「三宅島」を除くとparcelまでマッチ（阿古は地番データあり）
			name: "jat067-1 [東京都三宅村阿古497]",
			query: model.MatchQuery{
				Address:  "東京都三宅村阿古497",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "東京都三宅村阿古497",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "東京都",
				"county":        nil,
				"city":          "三宅村",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "阿古",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "497",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 建物名がないと「舞浜二丁目11番」と区別できない
			// ハイフン表記の場合、住居表示住所か地番住所か判別できないため、住居表示住所を優先してマッチ
			name: "jat068 [浦安市舞浜2-11ディズニーアンバサダーホテル]",
			query: model.MatchQuery{
				Address:  "浦安市舞浜2-11ディズニーアンバサダーホテル",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "千葉県浦安市舞浜2丁目11",
			wantUnmatchedAddress: []string{"ディズニーアンバサダーホテル"},
			wantStructured: map[string]any{
				"pref":          "千葉県",
				"county":        nil,
				"city":          "浦安市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "舞浜",
				"chome":         "2丁目",
				"koaza":         nil,
				"blk_num":       "11",
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 旧豊栄東栄町（とうえいちょう）、郵便番号950-3323
			// 同一漢字「東栄町」で読みが2種類存在：1-3丁目はトウエイチョウ、chome無しはヒガシサカエマチ
			name: "jat069 [新潟市北区東栄町1丁目1番14号]",
			query: model.MatchQuery{
				Address:  "新潟市北区東栄町1丁目1番14号",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "新潟県新潟市北区東栄町1丁目1-14",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "新潟県",
				"county":        nil,
				"city":          "新潟市",
				"ward":          "北区",
				"machiaza_dist": "トウエイチョウ",
				"kyoto_st":      nil,
				"oaza_cho":      "東栄町",
				"chome":         "1丁目",
				"koaza":         nil,
				"blk_num":       "1",
				"rsdt_num":      "14",
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 東栄町（ひがしさかえまち）、郵便番号950-3104
			// chome表記がない入力は、chome無し・地番専用の「ヒガシサカエマチ」レコード(machiaza_id=0095000)にマッチし、
			// "2番12" は prc_num1=2, prc_num2=12 として地番解釈される
			name: "jat070 [新潟市北区東栄町2番12]",
			query: model.MatchQuery{
				Address:  "新潟市北区東栄町2番12",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "新潟県新潟市北区東栄町2-12",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "新潟県",
				"county":        nil,
				"city":          "新潟市",
				"ward":          "北区",
				"machiaza_dist": "ヒガシサカエマチ",
				"kyoto_st":      nil,
				"oaza_cho":      "東栄町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "2",
				"prc_num2":      "12",
				"prc_num3":      nil,
			},
		},
		{
			// 広島県府中市の府中町（府中市立図書館）
			// 都道府県省略時、「府中市」は広島県にマッチ
			name: "jat071 [府中市府中町43]",
			query: model.MatchQuery{
				Address:  "府中市府中町43",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "広島県府中市府中町43",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "広島県",
				"county":        nil,
				"city":          "府中市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "府中町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "43",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat071の補足：「広島県」を明示的に付けても同じくparcelまでマッチ
			name: "jat071-1 [広島県府中市府中町43]",
			query: model.MatchQuery{
				Address:  "広島県府中市府中町43",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "広島県府中市府中町43",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "広島県",
				"county":        nil,
				"city":          "府中市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "府中町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "43",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 東京都府中市の府中町（府中警察署）
			// 注意：期待は東京都だが、現実装では広島県にマッチ
			name: "jat072 [府中市府中町1-10-5]",
			query: model.MatchQuery{
				Address:  "府中市府中町1-10-5",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "広島県府中市府中町",
			wantUnmatchedAddress: []string{"1-10-5"},
			wantStructured: map[string]any{
				"pref":          "広島県",
				"county":        nil,
				"city":          "府中市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "府中町",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat072の補足：「東京都」を付けるとparcelまでマッチ
			name: "jat072-1 [東京都府中市府中町1-10-5]",
			query: model.MatchQuery{
				Address:  "東京都府中市府中町1-10-5",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "東京都府中市府中町1丁目10-5",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "東京都",
				"county":        nil,
				"city":          "府中市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "府中町",
				"chome":         "1丁目",
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "10",
				"prc_num2":      "5",
				"prc_num3":      nil,
			},
		},
		{
			// 道路方式による住居表示住所
			// 「中島東通り」が大字名としてマッチ
			name: "jat073 [東根市中島東通り73]",
			query: model.MatchQuery{
				Address:  "東根市中島東通り73",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "山形県東根市中島東通り",
			wantUnmatchedAddress: []string{"73"},
			wantStructured: map[string]any{
				"pref":          "山形県",
				"county":        nil,
				"city":          "東根市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "中島東通り",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 街区符号が「渡辺」
			// 「渡辺」部分が消費され住居番号「3」のみ未マッチ
			// 注: 現在の出力は「久太郎町4丁目3」（blk_num=3）だが、これは誤マッチ
			// 本来は渡辺ブロック+rsdt_num=3でマッチすべき（別Issue）
			name: "jat074 [大阪市中央区久太郎町4丁目渡辺3]",
			query: model.MatchQuery{
				Address:  "大阪市中央区久太郎町4丁目渡辺3",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			// 渡辺は街区名として正しく認識される
			// AddColonで 久太郎町4丁目渡辺3 -> 久太郎町4丁目:渡辺-3 に変換
			wantMatchLevel:       model.MatchLevelResidentialDetail,
			wantMatchedAddress:   "大阪府大阪市中央区久太郎町4丁目渡辺-3",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "大阪府",
				"county":        nil,
				"city":          "大阪市",
				"ward":          "中央区",
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "久太郎町",
				"chome":         "4丁目",
				"koaza":         nil,
				"blk_num":       "渡辺",
				"rsdt_num":      "3",
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 丁目ではなく「丁」
			// 「西2丁」を認識、街区止まり（住居番号未マッチ）
			name: "jat075 [堺市堺区宿院町西2丁1番1号]",
			query: model.MatchQuery{
				Address:  "堺市堺区宿院町西2丁1番1号",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelResidentialBlock,
			wantMatchedAddress:   "大阪府堺市堺区宿院町西2丁1",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "大阪府",
				"county":        nil,
				"city":          "堺市",
				"ward":          "堺区",
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "宿院町西",
				"chome":         "2丁",
				"koaza":         nil,
				"blk_num":       "1",
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 数字の字（勝林寺）
			// 「三木町34」→ 小字「参四」(正規化形34) + 地番25 にマッチ（issue #259）
			name: "jat076 [石川県加賀市三木町34-25]",
			query: model.MatchQuery{
				Address:  "石川県加賀市三木町34-25",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "石川県加賀市三木町参四25",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "石川県",
				"county":        nil,
				"city":          "加賀市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "三木町",
				"chome":         nil,
				"koaza":         "参四",
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "25",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat076の補足：「34の」を明示的に付けるとmachiaza_detailまでマッチ
			name: "jat076-1 [石川県加賀市三木町34の]",
			query: model.MatchQuery{
				Address:  "石川県加賀市三木町34の",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiazaDetail,
			wantMatchedAddress:   "石川県加賀市三木町34の",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "石川県",
				"county":        nil,
				"city":          "加賀市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "三木町",
				"chome":         nil,
				"koaza":         "34の",
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat076の補足：「34の25」は「の」がハイフン化され jat076 と同じ解釈になる
			// （小字「参四」+ 地番25。issue #259）
			name: "jat076-2 [石川県加賀市三木町34の25]",
			query: model.MatchQuery{
				Address:  "石川県加賀市三木町34の25",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "石川県加賀市三木町参四25",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "石川県",
				"county":        nil,
				"city":          "加賀市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "三木町",
				"chome":         nil,
				"koaza":         "参四",
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "25",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// 大字名が「大」
			// CSVの期待値: oaza_cho=「大」、koaza=「字坪ノ内」、地番=573
			// しかしABRには「大」の下に「坪ノ内」や「字坪ノ内」のkoazaは存在しない
			// また「大字」削除処理により「大字坪ノ内」→「坪ノ内」となり「大」にマッチしない
			name: "jat077 [つくば市大字坪ノ内573]",
			query: model.MatchQuery{
				Address:  "つくば市大字坪ノ内573",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelCity,
			wantMatchedAddress:   "茨城県つくば市",
			wantUnmatchedAddress: []string{"大字坪ノ内573"},
			wantStructured: map[string]any{
				"pref":          "茨城県",
				"county":        nil,
				"city":          "つくば市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      nil,
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat077の補足：「大字」を付けずに「大573」とするとparcelマッチ
			name: "jat077-1 [茨城県つくば市大573]",
			query: model.MatchQuery{
				Address:  "茨城県つくば市大573",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelParcel,
			wantMatchedAddress:   "茨城県つくば市大573",
			wantUnmatchedAddress: nil,
			wantStructured: map[string]any{
				"pref":          "茨城県",
				"county":        nil,
				"city":          "つくば市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "大",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      "573",
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
		{
			// jat077の補足：「大字」を「大」にするとmachiazaマッチ（「坪ノ内」はABRに存在しない）
			name: "jat077-2 [つくば市大坪ノ内573]",
			query: model.MatchQuery{
				Address:  "つくば市大坪ノ内573",
				Category: model.CategoryAll,
				Pref:     "all",
				Limit:    1,
			},
			wantMatchLevel:       model.MatchLevelMachiaza,
			wantMatchedAddress:   "茨城県つくば市大",
			wantUnmatchedAddress: []string{"坪ノ内573"},
			wantStructured: map[string]any{
				"pref":          "茨城県",
				"county":        nil,
				"city":          "つくば市",
				"ward":          nil,
				"machiaza_dist": nil,
				"kyoto_st":      nil,
				"oaza_cho":      "大",
				"chome":         nil,
				"koaza":         nil,
				"blk_num":       nil,
				"rsdt_num":      nil,
				"rsdt_num2":     nil,
				"prc_num1":      nil,
				"prc_num2":      nil,
				"prc_num3":      nil,
			},
		},
	})
}
