## This workflow has been disabled for now, because the CKAN API is blocking our requests.
## Re-enable when we can package test data inside this repository.

name: "publish the code"

on:
  workflow_run:
    workflows: ["PR check"]
    types:
      - completed
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  publish:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Exit if not triggerred by pull_request
        run: |
          if [ "$triggered_by" = "push" ]; then
            echo "Triggered by push. Skipping."
            exit 0
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      #
      # build/ をダウンロード
      #
      - name: Download build output artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build/

      - name: Get the latest commit ID
        id: commit
        run: echo "commit_id=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: create changelog.md
        if: github.event_name != 'workflow_dispatch' 
        id: prepare
        run: |
          bash ./.github/workflows/generate_changelog.sh
          git add .
          git commit -m "create changelog.md"
          version=$(cat package.json | jq -r '.version')
          echo "version=$version" >> $GITHUB_OUTPUT
          tgz=$(npm pack | tail -n1 | tr -d '\n')
          echo "tgz=$tgz" >> $GITHUB_OUTPUT
          
      #
      # pull_requestの場合は、npm publish . --dry-run
      # workflow_dispatch(手動)の場合は、npm publish .
      #
      - name: npm release  (trigger / workflow_dispatch)
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            npm publish . --dry-run
            gh release create ${{ steps.prepare.outputs.version }}-${{ env.commit_id }} ${{ steps.prepare.outputs.tgz }}
          fi
          
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            gh release create ${{ steps.prepare.outputs.version }} ${{ steps.prepare.outputs.tgz }} 
            echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
            npm publish . --access public
          fi
        env:
          # GH_TOKEN: ${{ secrets.G_ACTIONS_TOKEN_FOR_PR }}
          GITHUB_TOKEN: ${{ secrets.G_ACTIONS_TOKEN_FOR_PR }}